### ISSUE TITLE
docker pull

### ISSUE THREAD

**Issue by ForestWang** [NVlabs/BundleSDF#1]
Hi:
when running "docker pull nvcr.io/nvidian/bundlesdf" get the error:
Error response from daemon: unauthorized: authentication required
so how to fix it？

**Comment by monajalal** [comment]
@ForestWang  build from scratch

**Comment by wenbowen123** [comment]
we are working on releasing the pre-built docker image, but there is not yet a clear timeline. 
Can you try build from scratch, as mentioned in readme option2?
