### ISSUE TITLE
 No module named Error "vos_wrapper"

### ISSUE THREAD

**Issue by takahiro2001kt** [NVlabs/BundleSDF#10]
I get a vos_wrapper error when running run_ho3d.py.
Details are as follows.

`Traceback (most recent call last):
  File "/content/drive/MyDrive/nvidia/BundleSDF-master/run_ho3d.py", line 16, in <module>
    from vos_wrapper import XmemRunner
ModuleNotFoundError: No module named 'vos_wrapper'`

The environment is Google Colaboratory.
Not use Docker

**Comment by wenbowen123** [comment]
Thanks for reporting this. Just pushed a fix.
