### ISSUE TITLE
step 3 for milk data --   File "run_custom.py", line 160, in postprocess_mesh     print(f"Using {mesh_files[-1]}") IndexError: list index out of range

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#100]
When running the third step

```
python run_custom.py --mode get_mesh --video_dir /home/bowen/debug/2022-11-18-15-10-24_milk --out_folder /home/bowen/debug/bundlesdf_2022-11-18-15-10-24_milk
```

for the milk data, I get this error:
```
(py38) root@mona-ThinkStation-P7:/home/mona/BundleSDF# python run_custom.py --mode get_mesh --video_dir /home/mona/BundleSDF/milk/2022-11-18-15-10-24_milk  --out_folder   /home/mona/BundleSDF/milk/2022-11-18-15-10-24_milk/out
Traceback (most recent call last):
  File "run_custom.py", line 227, in <module>
    postprocess_mesh(out_folder=args.out_folder)
  File "run_custom.py", line 160, in postprocess_mesh
    print(f"Using {mesh_files[-1]}")
IndexError: list index out of range

```

I believe it could be because of some of the errors I got in step 1 or 2.

Am I right and what should I do to fix this?

Also, this step expects "*normalized_space.obj" file which doesn't exist in out folder

```
(base) mona@mona-ThinkStation-P7:~/BundleSDF/milk/2022-11-18-15-10-24_milk/out$ find . -name "*normalized_space.obj"
(base) mona@mona-ThinkStation-P7:~/BundleSDF/milk/2022-11-18-15-10-24_milk/out$ 

```

**Comment by tomole444** [comment]
I encounter the same issue

**Comment by tomole444** [comment]
After some digging I found #28 and it looks like the 3rd stage is deprecated and you should already have the mesh in your output folder

**Comment by monajalal** [comment]
@tomole444 so what is the purpose of having step 3 in the README.md? @wenbowen123

**Comment by monajalal** [comment]
@tomole444 does it mean that your run also doesn't create this file?
 "*normalized_space.obj"

**Comment by tomole444** [comment]
> @tomole444 does it mean that your run also doesn't create this file? "*normalized_space.obj"

Yes that's correct. But it creates a mesh_cleaned.obj file which is the final mesh.

**Comment by tomole444** [comment]
> @tomole444 so what is the purpose of having step 3 in the README.md? @wenbowen123

I think the author didn't update the Readme yet.

**Comment by wenbowen123** [comment]
Yes, step3 is deprecated and you can skip. We will update it soon.
