### ISSUE TITLE
Hardware/ Software Requirements

### ISSUE THREAD

**Issue by pmdSchmidt** [NVlabs/BundleSDF#103]
Hi,

would it be possible to add the hardware and software requirements to the Readme?
Or can i find those somewhere?

Thank you!

**Comment by monajalal** [comment]
@pmdSchmidt min req GPU is RTX 3090 Ti w 24 G VRAM

**Comment by pmdSchmidt** [comment]
@monajalal okay, thank you! Now i don't wonder anymore why my jetson nano is having a hard time building
