### ISSUE TITLE
error in the step of "RUN imageio_download_bin freeimage",when docker building the dockerfile

### ISSUE THREAD

**Issue by hitWXF** [NVlabs/BundleSDF#107]
![2023-11-02 16-56-39屏幕截图](https://github.com/NVlabs/BundleSDF/assets/149487679/c055168a-db98-4bb2-a132-22a8242aea4f)
"OSError: Unable to download 'libfreeimage-3.16.0-linux64.so'. Perhaps there is no internet connection? If there is, please report this problem."

**Comment by wenbowen123** [comment]
Does your computer have internet connection? If you run `imageio_download_bin` in terminal without docker, does it work?

**Comment by hitWXF** [comment]
> Does your computer have internet connection? If you run `imageio_download_bin` in terminal without docker, does it work?

In the terninal without docker, I can run "imageio_download_bin". it will download the dynamic library file of 'libfreeimage-3.16.0-linux64.so', and save it to the local folder(/home/.imagio/freeimage). However, when i 'docker build' the dockerfile, error occurred. My computer has network restrictions. So i downloaded the 'libfreeimage-3.16.0-linux64.so' offline. But i do not know where i should save in docker with the command "COPY"

**Comment by wenbowen123** [comment]
can you build docker image on a computer with normal network, then transfer the docker image to your current machine?

**Comment by loubron23** [comment]
> > Does your computer have internet connection? If you run `imageio_download_bin` in terminal without docker, does it work?
> 
> In the terninal without docker, I can run "imageio_download_bin". it will download the dynamic library file of 'libfreeimage-3.16.0-linux64.so', and save it to the local folder(/home/.imagio/freeimage). However, when i 'docker build' the dockerfile, error occurred. My computer has network restrictions. So i downloaded the 'libfreeimage-3.16.0-linux64.so' offline. But i do not know where i should save in docker with the command "COPY"
@hitWXF Hello,I have the sanme problem, could you please tell me how you solved it at last?

**Comment by hitWXF** [comment]
> > > Does your computer have internet connection? If you run `imageio_download_bin` in terminal without docker, does it work?
> > 
> > 
> > In the terninal without docker, I can run "imageio_download_bin". it will download the dynamic library file of 'libfreeimage-3.16.0-linux64.so', and save it to the local folder(/home/.imagio/freeimage). However, when i 'docker build' the dockerfile, error occurred. My computer has network restrictions. So i downloaded the 'libfreeimage-3.16.0-linux64.so' offline. But i do not know where i should save in docker with the command "COPY"
> > @hitWXF Hello,I have the sanme problem, could you please tell me how you solved it at last?

hello，you can download the  'libfreeimage-3.16.0-linux64.so' offline，and put it under the “libsource” folder, then, put the  “libsource” folder under the "docker" folder.
You should replace the command "RUN imageio_download_bin freeiamge" with the command "COPY ./libsource/libfreeimage-3.16.0-linux64.so /.imageio/freeimage" 
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=8005361435025219339 skey=@crypt_6d030eb2_3a6234c1159a6e5f5254bd975c54aed7 mmweb_appid=wx_webfilehelper](https://github.com/NVlabs/BundleSDF/assets/149487679/e5967d3c-3126-45a0-8a53-e39c0b857cec)
