### ISSUE TITLE
How to access the visualizations of 6D pose or Visualize the 6D pose after running the commands?

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#108]
When I was running the commands, I got these but I am interested in accessing the visualizations for the 6DoF pose like the ones you have in the gifs below. Could you please share the code that visualizes the poses for each frame (a set of frames) after they are processed and now that you have the annotations? I notice this issue https://github.com/NVlabs/BundleSDF/issues/91 but it is about during the processing. Also, as you see below, during processing I only get the orientation visualization not the 3D tight bounding box as your gifs.

![image](https://github.com/NVlabs/BundleSDF/assets/1892917/899e2b3b-de3a-4cee-a9f0-beaab8f52219)

![milk_jug](https://github.com/NVlabs/BundleSDF/assets/1892917/55838609-14a5-48d4-b61f-6a982ce41e7e)
![problem_setup_c](https://github.com/NVlabs/BundleSDF/assets/1892917/1d191a4f-8762-4e67-a35b-5966de56dad9)

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/BundleSDF/issues/91 gives you the viz after running, instead of during running. Is that what you are asking? If you want a box overlay on the gui, you can also refer to that code.

**Comment by Wahaha-code** [comment]
I think we have the same problem, how to generate tight edges like a mask when visualizing instead of a rectangular box
