### ISSUE TITLE
Multi-object 6D pose estimation

### ISSUE THREAD

**Issue by junho-choi-div** [NVlabs/BundleSDF#112]
Hi, may I know if BundleSDF methodology works well with multiple objects? In the given data, I think I'm good at 6D estimation for a single object, but if there are multiple objects placed in one frame, I wonder if I'm good at 6D estimation even then. Also, I wonder if they perform well even when objects overlap each other.Thanks!

**Comment by wenbowen123** [comment]
For multi-object, currently there is no mechanism to solve all of them at once. You need to run bundlesdf multiple times.  Each time only mask one object of interest. The occlusion (overlap) between them shouldn't affect, as bundlesdf is robust to occlusions (as shown by the human-object interaction examples).
