### ISSUE TITLE
bash build.sh occur this error

### ISSUE THREAD

**Issue by Wahaha-code** [NVlabs/BundleSDF#120]
bash build.sh occur this error
`  _write_ninja_file_and_compile_objects(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
-- The CUDA compiler identification is unknown
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
CMake Error at /usr/share/cmake-3.16/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/gww/project/BundleSDF-master/BundleTrack/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_c4472/fast && /usr/bin/make -f CMakeFiles/cmTC_c4472.dir/build.make CMakeFiles/cmTC_c4472.dir/build
    make[1]: Entering directory '/home/gww/project/BundleSDF-master/BundleTrack/build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_c4472.dir/main.cu.o
    /usr/local/cuda/bin/nvcc     -x cu -c /home/gww/project/BundleSDF-master/BundleTrack/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_c4472.dir/main.cu.o
    gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
    compilation terminated.
    nvcc fatal   : Failed to preprocess host compiler properties.
    make[1]: *** [CMakeFiles/cmTC_c4472.dir/build.make:66: CMakeFiles/cmTC_c4472.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/home/gww/project/BundleSDF-master/BundleTrack/build/CMakeFiles/CMakeTmp'
    make: *** [Makefile:121: cmTC_c4472/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)
`

**Comment by wenbowen123** [comment]
what's the output if you run `nvcc -V` in the terminal inside docker?

**Comment by Wahaha-code** [comment]
(py38) root@116-172-93-173:/home/gww/project/BundleSDF-master# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**Comment by Wahaha-code** [comment]
The cuda of my server is 12

**Comment by omercahit** [comment]
same error
`gcc: fatal error: cannot execute 'cc1plus': execvp: No such file or directory
compilation terminated.`

**Comment by Wahaha-code** [comment]
I have solved it after putting the project in docker and then running it.

**Comment by Jimmy-puppy** [comment]
@Tharun-tharun same issue,have you fixed it?
