### ISSUE TITLE
Bounding box rotation and size is wrong for some custom objects

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#124]
Dear @wenbowen123 

While the produced projected 3D bounding boxes are correct for some objects (e.g. blue cup), it is not correct for this custom object we had in the lab. Could you please guide what could be wrong and some guidance on how to fix it? The orientation is shown correctly.

![Screenshot from 2023-11-22 10-56-53](https://github.com/NVlabs/BundleSDF/assets/1892917/414be582-ac19-40ae-8942-4f4fae89293c)

This is actually the first frame in the capture. All of the other frames are accordingly have wrong 3D bounding boxes.

![Screenshot from 2023-11-22 11-16-47](https://github.com/NVlabs/BundleSDF/assets/1892917/ab45fc8a-7e47-4f64-bb4c-5790816b25cc)

**Comment by monajalal** [comment]
I did a capture for a much simpler object and still have the same problem
![Screenshot from 2023-11-22 12-48-05](https://github.com/NVlabs/BundleSDF/assets/1892917/a20042ae-e057-43ec-9791-410f3960cbd9)

In this special case, the center of object where orientation visualization is shown is also not located properly 

![image](https://github.com/NVlabs/BundleSDF/assets/1892917/6b65030a-b1ff-4418-8f82-c5259e2809b7)

**Comment by monajalal** [comment]
I changed the z-far from 1 meter to 1.2 and I get the bbox in correct location but not correct orientation, also when changing it to .9 caused errors. My object was approximately 1m away from the non-moving camera on a tripod.

![Screenshot from 2023-11-22 15-14-18](https://github.com/NVlabs/BundleSDF/assets/1892917/0cb67c2e-bd5c-4294-a576-5d3942b71e66)


Please let me know if you have any suggestions as how to fix the orientation of the bbox? This is btw the first frame.

**Comment by wenbowen123** [comment]
the drawing of the bounding box will only be correct after you finish the entire run, since It needs the complete shape to find the correct orientation.

**Comment by monajalal** [comment]
So, I ran the whole thing again, the mesh is not fully recovered correctly (back of mesh is weird), and the orientation (and somewhat size of) bounding box is wrong in the first frame. Could you suggest what can be fixed?

![image](https://github.com/NVlabs/BundleSDF/assets/1892917/ef5e06ba-3ca7-4d38-acff-72cd4c07a600)

![Screenshot from 2023-11-27 09-31-30](https://github.com/NVlabs/BundleSDF/assets/1892917/d7624a6e-2b39-4c4c-b24c-d0fc63b5f8cd)


here is the link for the log of first step https://drive.google.com/file/d/1JlhCFFRuHNLWlBSC-j_rp1h_ERDaElCg/view?usp=sharing

**Comment by monajalal** [comment]
I changed the z-far to 1.1 in run_custom.py

I have this mesh which is correct for the most part
![Screenshot from 2023-11-27 12-33-59](https://github.com/NVlabs/BundleSDF/assets/1892917/1cddd40d-8815-4223-88d6-b070f5c25c2a)


however, the bounding box is not as tight as you would expect it and its rotation is slightly off. I am showing the bbox for first frame
![Screenshot from 2023-11-27 12-31-59](https://github.com/NVlabs/BundleSDF/assets/1892917/0cb759fa-808a-4065-b312-a4766ec7630a)


here's the log of step 1 https://drive.google.com/file/d/1lPlltKQ2edBd6Ymy8sJR5tTFfqqqftsA/view?usp=sharing

here's the log of global refinement https://drive.google.com/file/d/151iQgklybfxkLplaLnnZWAHQIxhavy3N/view?usp=sharing
