### ISSUE TITLE
Docker building doesn't finish

### ISSUE THREAD

**Issue by DomaradzkiMaciej** [NVlabs/BundleSDF#125]
Hi, how long should building a docker image takes?
In my case, the first 5 stages took little time and 6th stage with opencv stops at 98% percent and even after 5 hours nothing change.

![image](https://github.com/NVlabs/BundleSDF/assets/56363057/c7614eca-9369-4a2a-bebd-ab07d8f15846)

**Comment by wenbowen123** [comment]
Not sure why it's that slow. Is it still actively running or zombie? 
Alternatively, there are some pre-built docker image on docker hub that you might want to try.

**Comment by zahid990170** [comment]
@DomaradzkiMaciej were you able to follow on the next step ? i.e.  `bash run_container.sh
`
