### ISSUE TITLE
3D reconstruction consultation

### ISSUE THREAD

**Issue by cynthia-you** [NVlabs/BundleSDF#126]
Hi 温老师~
After try bundleSDF on GTX1066 ti( loftr always failed), i pulled image on rtx3070, and it run successfully (run_video/global_refine/draw_pose).
But the generated 3d mesh(textured_mesh.obj) appears to come from the perspective of a particular frame, not the starting or ending frame.
I'm wondering how can i get the completed mesh just like the readme.md showed(the drill demo) , thanks~~~~~

**Comment by wenbowen123** [comment]
The mesh should be complete. Did you rotate the mesh to viz from a different perspective?

**Comment by cynthia-you** [comment]
![Screenshot from 2023-11-30 15-27-56](https://github.com/NVlabs/BundleSDF/assets/37206493/0fb42fe9-8cc8-4c49-aba5-e82037074dbb)
![Screenshot from 2023-11-30 15-28-16](https://github.com/NVlabs/BundleSDF/assets/37206493/0dd6cc27-1d50-4177-8c97-4594abec1510)


after run 'global_refine'  only  mesh_cleaned.obj and textured_mesh.obj generated, and i droped the obj in Meshlab.

**Comment by cynthia-you** [comment]
> The mesh should be complete. Did you rotate the mesh to viz from a different perspective?

A, i see, it is becuz every time i run the bundlesdf, the 3d reconsturction results are diffrent:
![Screenshot from 2023-11-30 16-50-18](https://github.com/NVlabs/BundleSDF/assets/37206493/d4a13413-ca7f-4caa-bf71-83b8f50dfa7f)
![Screenshot from 2023-11-30 17-25-54](https://github.com/NVlabs/BundleSDF/assets/37206493/a0fe0d8e-45cd-4f60-871a-3c37edc0b003)

**Comment by cynthia-you** [comment]
######################### another Q ##########
When i run dataset 'milk' no Pdb showed, but  in my customed dataset , i must manually enter 'c' every epoch, can i do sth to revise that? 
![Screenshot from 2023-12-01 09-22-13](https://github.com/NVlabs/BundleSDF/assets/37206493/92b658eb-5d73-49da-bde7-7c7df30c2d1a)

**Comment by Jingranxia** [comment]
> ######################### another Q ########## When i run dataset 'milk' no Pdb showed, but in my customed dataset , i must manually enter 'c' every epoch, can i do sth to revise that? ![Screenshot from 2023-12-01 09-22-13](https://private-user-images.githubusercontent.com/37206493/287116965-92b658eb-5d73-49da-bde7-7c7df30c2d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk3NTYsIm5iZiI6MTcwMTc1OTQ1NiwicGF0aCI6Ii8zNzIwNjQ5My8yODcxMTY5NjUtOTJiNjU4ZWItNWQ3My00OWRhLWJkZTctN2M3ZGYzMGMyZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWI4OGQwZjRhNDkyYzQ5YmRjMjZhMjBkNDliOGY5MDgyMDFiODY4YzViODk3MzBlOTc2NjZkOTFlYTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBpNRj2SQfO-G9-6p_zIOILszg6ny6fTI5-CmGaxM6w)

你这里是连续帧出了问题吧，没有匹配上

**Comment by cynthia-you** [comment]
> > ######################### another Q ########## When i run dataset 'milk' no Pdb showed, but in my customed dataset , i must manually enter 'c' every epoch, can i do sth to revise that? ![Screenshot from 2023-12-01 09-22-13](https://private-user-images.githubusercontent.com/37206493/287116965-92b658eb-5d73-49da-bde7-7c7df30c2d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk3NTYsIm5iZiI6MTcwMTc1OTQ1NiwicGF0aCI6Ii8zNzIwNjQ5My8yODcxMTY5NjUtOTJiNjU4ZWItNWQ3My00OWRhLWJkZTctN2M3ZGYzMGMyZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWI4OGQwZjRhNDkyYzQ5YmRjMjZhMjBkNDliOGY5MDgyMDFiODY4YzViODk3MzBlOTc2NjZkOTFlYTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBpNRj2SQfO-G9-6p_zIOILszg6ny6fTI5-CmGaxM6w)
> 
> 你这里是连续帧出了问题吧，没有匹配上

有可能的，但是不管是示例数据集还是自制数据集都频繁发生最后的mesh残缺。

**Comment by Jingranxia** [comment]
> > > ######################### another Q ########## When i run dataset 'milk' no Pdb showed, but in my customed dataset , i must manually enter 'c' every epoch, can i do sth to revise that? ######![Screenshot from 2023-12-01 09-22-13](https://private-user-images.githubusercontent.com/37206493/287116965-92b658eb-5d73-49da-bde7-7c7df30c2d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk3NTYsIm5iZiI6MTcwMTc1OTQ1NiwicGF0aCI6Ii8zNzIwNjQ5My8yODcxMTY5NjUtOTJiNjU4ZWItNWQ3My00OWRhLWJkZTctN2M3ZGYzMGMyZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWI4OGQwZjRhNDkyYzQ5YmRjMjZhMjBkNDliOGY5MDgyMDFiODY4YzViODk3MzBlOTc2NjZkOTFlYTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBpNRj2SQfO-G9-6p_zIOILszg6ny6fTI5-CmGaxM6w)
> > 
> > 
> > 你这里是连续帧出了问题吧，没有匹配上
> 
> 有可能的，但是不管是示例数据集还是自制数据集都频繁发生最后的mesh残缺。

作者的示例数据集生成的瓶口处是会残缺的，如果别的地方也残缺了，那就是环境可能不对

**Comment by wenbowen123** [comment]
>A, i see, it is becuz every time i run the bundlesdf, the 3d reconsturction results are diffrent:

This is weird. Overall the mesh should be fairly similar. Another weird thing is your texture seems black. Did you try HO3D data as well?

**Comment by cynthia-you** [comment]
> > A, i see, it is becuz every time i run the bundlesdf, the 3d reconsturction results are diffrent:
> 
> This is weird. Overall the mesh should be fairly similar. Another weird thing is your texture seems black. Did you try HO3D data as well?


Cuze the meash and material_0.png are incompleted, so the mesh looks black on some view, if i rotate the mesh , the missing parts will be more visible.  
And  in the process of neural field training, the error is very big, the error is up to 1X on rgb_loss and sdf_loss, so the model is incomplete(my assumption).
I havent try HO3D yet.

**Comment by wenbowen123** [comment]
in many sense, this is abnormal, though I do not have any clues. Did you make any local changes to the code? I'd recommend to start from scratch (cloning the repo, restart docker, etc).

**Comment by 52THANOS** [comment]
> > > ######################### another Q ########## When i run dataset 'milk' no Pdb showed, but in my customed dataset , i must manually enter 'c' every epoch, can i do sth to revise that? ![Screenshot from 2023-12-01 09-22-13](https://private-user-images.githubusercontent.com/37206493/287116965-92b658eb-5d73-49da-bde7-7c7df30c2d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk3NTYsIm5iZiI6MTcwMTc1OTQ1NiwicGF0aCI6Ii8zNzIwNjQ5My8yODcxMTY5NjUtOTJiNjU4ZWItNWQ3My00OWRhLWJkZTctN2M3ZGYzMGMyZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWI4OGQwZjRhNDkyYzQ5YmRjMjZhMjBkNDliOGY5MDgyMDFiODY4YzViODk3MzBlOTc2NjZkOTFlYTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBpNRj2SQfO-G9-6p_zIOILszg6ny6fTI5-CmGaxM6w)
> > 
> > 
> > 你这里是连续帧出了问题吧，没有匹配上
> 
> 有可能的，但是不管是示例数据集还是自制数据集都频繁发生最后的mesh残缺。



> > > ######################### another Q ########## When i run dataset 'milk' no Pdb showed, but in my customed dataset , i must manually enter 'c' every epoch, can i do sth to revise that? ![Screenshot from 2023-12-01 09-22-13](https://private-user-images.githubusercontent.com/37206493/287116965-92b658eb-5d73-49da-bde7-7c7df30c2d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTk3NTYsIm5iZiI6MTcwMTc1OTQ1NiwicGF0aCI6Ii8zNzIwNjQ5My8yODcxMTY5NjUtOTJiNjU4ZWItNWQ3My00OWRhLWJkZTctN2M3ZGYzMGMyZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZWI4OGQwZjRhNDkyYzQ5YmRjMjZhMjBkNDliOGY5MDgyMDFiODY4YzViODk3MzBlOTc2NjZkOTFlYTY4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sBpNRj2SQfO-G9-6p_zIOILszg6ny6fTI5-CmGaxM6w)
> > 
> > 
> > 你这里是连续帧出了问题吧，没有匹配上
> 
> 有可能的，但是不管是示例数据集还是自制数据集都频繁发生最后的mesh残缺。

可以私下交流一下吗，我有些问题
