### ISSUE TITLE
Only the mask of the first frame is needed, how should I set up the mosaic that only uses the first frame.

### ISSUE THREAD

**Issue by Wahaha-code** [NVlabs/BundleSDF#128]
Dear author, it is said in the paper that only the mask of the first frame is needed, but looking at the milk data set, it seems that we have obtained the masks of all frames, and they will certainly be used in run_one_video.

**Comment by wenbowen123** [comment]
mentioned in readme https://github.com/NVlabs/BundleSDF#run-on-your-custom-data
