### ISSUE TITLE
About installing on different operating systems

### ISSUE THREAD

**Issue by Jingranxia** [NVlabs/BundleSDF#130]
Hello author, I would like to deploy your model on Windows. Is it possible to implement it? Some libraries only support Ubuntu

**Comment by wenbowen123** [comment]
Hi, if you use docker, it should work on Windows as well.

**Comment by Jingranxia** [comment]
> Hi, if you use docker, it should work on Windows as well.

Hello, what I mean is that deploying algorithms locally on Windows without using Docker is possible

**Comment by wenbowen123** [comment]
Unfortunately, we only support docker as for now.

**Comment by 52THANOS** [comment]
> Unfortunately, we only support docker as for now.

温老师我问一下ERROR: failed to solve: process "/bin/bash --login -c imageio_download_bin freeimage" did not complete successfully: exit code: 1 build dockerfile的时候出现这个问题怎么办

**Comment by wenbowen123** [comment]
@52THANOS  someone seems to have found the solution https://github.com/NVlabs/BundleSDF/issues/107
