### ISSUE TITLE
CANT COMPREHEND README! HOW TO RUN THE CONTAINER ?

### ISSUE THREAD

**Issue by 52THANOS** [NVlabs/BundleSDF#131]
after i built a container using the image , the container shows it is running,but i cant bash build.sh. it seems the environment of this container is wrong.
![image](https://github.com/NVlabs/BundleSDF/assets/117810189/713367d1-473d-45f6-9b01-c3f6f1586906)
![image](https://github.com/NVlabs/BundleSDF/assets/117810189/d2187844-6ba9-4f98-bfff-9c83ea59f752)
it shows that im in docker-desktop ,and i cant find my bundlesdf file. 
im confused. do i have to copy bundlesdf into this container?

**Comment by 52THANOS** [comment]
what directory structure it is

**Comment by fedona** [comment]
Once you activated the docker image through the bash script that is provided, you then have to navigate to the location of the BundleSDF folder yourself, I do not know where you have it, but start going to /local/home/<username> might be a good idea.

Once you are in the correct folder you should be able to see the same files that are in this repository and to run the milk example.

**Comment by 52THANOS** [comment]
> Once you activated the docker image through the bash script that is provided, you then have to navigate to the location of the BundleSDF folder yourself, I do not know where you have it, but start going to /local/home/ might be a good idea.
> 
> Once you are in the correct folder you should be able to see the same files that are in this repository and to run the milk example.

what if i want to run the RGBD video. you guys did not supply this script

**Comment by fedona** [comment]
I recommend you to first run the milk example and then eventually try to run your own RGBD datasets.

For you own dataset you must be sure the RGB and D images have same camera calibration and resolution. Do not forget to include camera calibration file and to organize datas as in the milk example folder.

All necessary commands are given in the readme file.

p.s. I am not author in this project but I am sure they will be glad to help you, just note that caps lock is somehow a bit intimidating to use.

**Comment by kevinDrawn** [comment]
Is it possible to use algorithms with real-time camera images?

**Comment by wenbowen123** [comment]
@fedona  is correct, once you enter docker container, you need to go to the dir of the codebase, which is the same as on your local.

**Comment by kevinDrawn** [comment]
Wow! Great!! Is this a complete project? If not, when can I utilize it?

**Comment by wenbowen123** [comment]
@kevinDrawn It's completed but under review. We will release the code soon after it's accepted.

**Comment by 52THANOS** [comment]
solved

**Comment by kevinDrawn** [comment]
Wow Thank you so much! I will utilize your new algorithm to make my study.
