### ISSUE TITLE
segmentation fault(core dumped)

### ISSUE THREAD

**Issue by HappySalamander** [NVlabs/BundleSDF#133]
Hi, Thank you for your research.

I don't use conda in Dockerfile, just use pip and i can't use xhost.

Somehow I built a docker. but if i run, it can't work.

Please give me some comment.

root@gnode3:/home/lsy/working/BundleSDF# python3 run_ho3d.py --video_dirs /home/lsy/working/BundleSDF/BundleTrack/HO3D_v3/evaluation/SM1 --out_dir /home/lsy/working/BundleSDF/BundleTrack/result/ho3d_ours
video_dirs:
 ['/home/lsy/working/BundleSDF/BundleTrack/HO3D_v3/evaluation/SM1']
default_cfg {'backbone_type': 'ResNetFPN', 'resolution': (8, 2), 'fine_window_size': 5, 'fine_concat_coarse_feat': True, 'resnetfpn': {'initial_dim': 128, 'block_dims': [128, 196, 256]}, 'coarse': {'d_model': 256, 'd_ffn': 256, 'nhead': 8, 'layer_names': ['self', 'cross', 'self', 'cross', 'self', 'cross', 'self', 'cross'], 'attention': 'linear', 'temp_bug_fix': False}, 'match_coarse': {'thr': 0.2, 'border_rm': 2, 'match_type': 'dual_softmax', 'dsmax_temperature': 0.1, 'skh_iters': 3, 'skh_init_bin_score': 1.0, 'skh_prefilter': True, 'train_coarse_percent': 0.4, 'train_pad_num_gt_min': 200}, 'fine': {'d_model': 128, 'd_ffn': 128, 'nhead': 8, 'layer_names': ['self', 'cross'], 'attention': 'linear'}}
[bundlesdf.py] processNewFrame start 0000
[bundlesdf.py] process frame 0000
Segmentation fault (core dumped)

Thank you.

**Comment by wenbowen123** [comment]
you said you built a docker, is that the same as the one we provided? And when you enter the docker, was the conda env sourced?

**Comment by HappySalamander** [comment]
i don't use conda. i use venv.

but if i use custom data not ho3d, it works. 

by the way, Can you do it in real time using an rgbd camera?

Thanks.

**Comment by wenbowen123** [comment]
It's recommended to pre-collect the video offline for 3d reconstruction with BundleSDF. Once you have the 3D model and want to do real-time pose estimation/tracking, please checkout our recent work [FoundationPose](https://nvlabs.github.io/FoundationPose/).

**Comment by HappySalamander** [comment]
Thanks for your answer.

I think the project you recommended fits my purpose.

I want a 6D Pose tracking for an unknown multi-object in a real-time video. 

Thanks for your research.
