### ISSUE TITLE
Can Ubuntu 18.04 Version run this code?

### ISSUE THREAD

**Issue by kevinDrawn** [NVlabs/BundleSDF#134]
Hello. 

I'm struggling to run 

"python run_custom.py --mode run_video --video_dir /home/bowen/debug/2022-11-18-15-10-24_milk --out_folder /home/bowen/debug/bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 1 --debug_level 2"

And I had installed the libyaml-cpp0.7.0 for running this code.

But There are dependency.

 libyaml-cpp0.7:amd64 depends on libc6 (>= 2.32); however:
  Version of libc6:amd64 on system is 2.27-3ubuntu1.6.
 libyaml-cpp0.7:amd64 depends on libgcc-s1 (>= 3.3.1); however:
  Package libgcc-s1:amd64 is not configured yet.
 libyaml-cpp0.7:amd64 depends on libstdc++6 (>= 11); however:
  Version of libstdc++6:amd64 on system is 8.4.0-1ubuntu1~18.04.

But, Ubuntu 18.04 can't upgrade the libc6 version over 2.7.

There is ubuntu version limit to run this code?

**Comment by wenbowen123** [comment]
Hi, we haven't tested on Ubuntu 18. We recommend to use docker to reduce the env setup issues.

**Comment by kevinDrawn** [comment]
Thank you for your response
