### ISSUE TITLE
How can i get pyrealsense2.so ?

### ISSUE THREAD

**Issue by kevinDrawn** [NVlabs/BundleSDF#136]
Ubuntu 20.04
Python 3.8 

Hello.

I want to import pyrealsense2.

So, I tried the below process.
```

cmake 
cmake ../ -DBUILD_PYTHON_BINDINGS:bool=true -DPYTHON_EXECUTABLE=/usr/bin/python3

make -j6

sudo make install


```

All process was clear. But In my /usr/local/lib,

There isn't library related to pyrealsense2.so 

`(base) park@park-MS-7D42:/usr/local/lib$ ls
cmake                       librealsense2-gl.so.2.54.2  librealsense-file.a
libfw.a                     librealsense2.so            librsutils.a
librealsense2-gl.so         librealsense2.so.2.50       pkgconfig
librealsense2-gl.so.2.50    librealsense2.so.2.50.0     python3.8
librealsense2-gl.so.2.50.0  librealsense2.so.2.54
librealsense2-gl.so.2.54    librealsense2.so.2.54.2`

How can i install the pyrealsense2.so?

@MartyG-RealSense

**Comment by MartyG-RealSense** [comment]
Hi @kevinDrawn  Do you have a path called **librealsense/build/wrappers/python** please?  If you do, are the .so files located there?

![image](https://github.com/NVlabs/BundleSDF/assets/41145062/006e2929-2bfa-4faa-b93e-14a2dc2d8d10)

**Comment by kevinDrawn** [comment]
![Uploading Screenshot from 2024-01-26 17-52-45.png…]()
no one..

**Comment by MartyG-RealSense** [comment]
If you are able to use **pip install** commands on your computer then another way to install the wrapper is with the command **pip install pyrealsense2**

**Comment by kevinDrawn** [comment]
Oh, I success to install it by using pip.

```
(base) park@park-MS-7D42:~/Downloads/pycharm-2023.3.2$ pip install pyrealsense2
Defaulting to user installation because normal site-packages is not writeable
Collecting pyrealsense2
  Downloading pyrealsense2-2.54.2.5684-cp38-cp38-manylinux1_x86_64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 9.8 MB/s 
Installing collected packages: pyrealsense2
Successfully installed pyrealsense2-2.54.2.5684

```

**Comment by MartyG-RealSense** [comment]
Great!  Please do let me know if you have any further problems.

**Comment by kevinDrawn** [comment]
Do you know Where is the pyrealsense2.so file?? 

I want to set the Python Path to find the pyrealsense2 library. How can i find the location??

**Comment by MartyG-RealSense** [comment]
You would only need to know the location of the .so file if you wanted to copy the file into the same folder as your Python script.  If pyrealsense2 is able to find your Python 3 installation then copying the file is not necessary.

Please try running a pyrealsense2 test script to see whether it works.  A script with one line should be enough to test whether pyrealsense2 and Python 3 can talk to each other correctly.

`import pyrealsense2 as rs`

**Comment by kevinDrawn** [comment]
OH!!! I Solved problem!! There was not no module error! 

Thank you a lot bro!

**Comment by MartyG-RealSense** [comment]
You are very welcome  :)

**Comment by wenbowen123** [comment]
Hi, another tip is the data collection with realsense could be separated from this repo. You can prepare your own video like the demo data's structure beforehand if you have trouble setting up realsense env inside docker.
