### ISSUE TITLE
How can I make mask images from my custom rgb data?

### ISSUE THREAD

**Issue by kevinDrawn** [NVlabs/BundleSDF#137]
Hello! I really appreciate your amazing work, thank you! 

I want to try using the bundlesdf algorithm with images I've taken myself! But, I'm struggling because I don't have a way to create masks. It seems like if I set use_segmenter to 1 and run run_custom.py, I might be able to get mask images from my existing RGB images, is that correct? 

Would I need to modify the code or is there any preparation I need to do beforehand?

**Comment by wenbowen123** [comment]
see https://github.com/NVlabs/BundleSDF/issues/141
