### ISSUE TITLE
How to replicate inference speed mentioned in paper?

### ISSUE THREAD

**Issue by NJ-WuSiyang** [NVlabs/BundleSDF#138]
Thanks for the amazing work.

I run the code for HO3D locally, following the same command [here](https://github.com/NVlabs/BundleSDF?tab=readme-ov-file#run-on-ho3d-dataset)(`python run_ho3d.py`) in README. My desktop has a RTX 3090 GPU (which is the same as the device mentioned in the paper) and 12 Intel i5-12400 CPUs. I test the inference speed by timing every iteration of this [for loop](https://github.com/NVlabs/BundleSDF/blob/master/run_ho3d.py#L53). The speed on my desktop is around $0.4Hz$, much slower than $10.2Hz$ reported in the paper. Why is it so slow on my desktop? Do I time inference time correctly? Or is there any hyperparameter that I need to change?

Thanks in advance.

**Comment by wenbowen123** [comment]
duplicate https://github.com/NVlabs/BundleSDF/issues/45
