### ISSUE TITLE
Adding Segmentation Wrapper

### ISSUE THREAD

**Issue by NicCusinato** [NVlabs/BundleSDF#141]
What code should be added to the segmentation_utils.py for the Xmem wrapper? Also should I rebuilt the image or container?

**Comment by wenbowen123** [comment]
there is no need to rebuild. The wrapper is just an example to resemble our original pipeline (XMem removed due to license issue). You could also use SAM or tools like [this](https://github.com/hkchengrex/XMem/blob/main/docs/DEMO.md) to obtain the masks.
