### ISSUE TITLE
How make custom data?

### ISSUE THREAD

**Issue by lsy-92** [NVlabs/BundleSDF#142]
Hello!

Thanks to your great job!

i try to make a custom data.

i already made color image, depth image using Orbbec Femto.

then i make mask image using XMem.

But, BundleSDF doesn't work.

I don't understand other issue. what is different with your custom milk data?

![error](https://github.com/NVlabs/BundleSDF/assets/100773530/1c9e38de-a30e-43d0-837e-df33425d90d3)

**Comment by wenbowen123** [comment]
It's hard to tell from the limited info. A common pitfall is the depth data format, which should be uint16 PNG. Or you can use raw npy file and change the loading in the code.

**Comment by HappySalamander** [comment]
i made it Y16 format. it is 16bit image. so it is not problem.
and how can I get cam_K.txt?
i read Femto camera parameter, but it is an identity matrix.

**Comment by wenbowen123** [comment]
depth should not depend on masks, so no. You might want to make sure after you read  the depth image using the code, you are getting the right numbers.

Identity is certainly not right. Please check their manual/github.

**Comment by HappySalamander** [comment]
i check your depth image's numpy. 

that maximum value is 4. 

i want to know how you nomalized that.

![image](https://github.com/NVlabs/BundleSDF/assets/100773530/11f8cbea-c034-48f3-bf58-63b77dcbf352)

**Comment by wenbowen123** [comment]
suppose you have the depth data in meters, you can save to PNG by
`cv2.imwrite(dir, (depth*1000).astype(np.uint16))`

**Comment by HappySalamander** [comment]
my depth image is (480, 640, 3) as numpy.

but it's value is in 0~255.

i want to make this image like your depth image. 

![image](https://github.com/NVlabs/BundleSDF/assets/100773530/0f9707e5-cc96-4abe-8a4f-dbc978fa090a)

**Comment by wenbowen123** [comment]
How did you obtain this image?

**Comment by HappySalamander** [comment]
I use depth estimate model.

but it doesn't look like your depth image.

did you do postprocess your depth image?

**Comment by wenbowen123** [comment]
the depth image are the raw data from depth camera. If you use depth estimation model, make sure you are  getting the metric depth.

**Comment by lsy-92** [comment]
I use Zoe Depth metric depth model. but it doesn't work well in BundleSDF. I try tunning parameter RANSAC, or zfar, or depth weight, but it doesn't work. what shoud i do?

**Comment by wenbowen123** [comment]
using monocular depth estimation to get depth could be highly uncertain for both metric depth and relatively depth quality. I'd suggest to try with a depth camera.

**Comment by lsy-92** [comment]
I have another question. how can i evaluate a custom data result?

How can i make gt?

I always feel grateful for your kind answer.

**Comment by lsy-92** [comment]
![image](https://github.com/NVlabs/BundleSDF/assets/100773530/e4858cbf-91d9-4515-948c-3e1aa525d2e4)
i make Custom Dataset using Femto camera.

but bottle's nerf back part does not make well.

how can i fix it?

**Comment by wenbowen123** [comment]
from the GUI, can you tell if the tracking is lost?

**Comment by lsy-92** [comment]
![image](https://github.com/NVlabs/BundleSDF/assets/100773530/4bb34412-2d6a-4588-b4e3-a2f0608cdd62)
![image](https://github.com/NVlabs/BundleSDF/assets/100773530/66dcb59e-6964-47b8-876d-2771032a089d)

It's a little wrong, but I think it went well.

**Comment by JINAOLONG** [comment]
> Hello!
> 
> Thanks to your great job!
> 
> i try to make a custom data.
> 
> i already made color image, depth image using Orbbec Femto.
> 
> then i make mask image using XMem.
> 
> But, BundleSDF doesn't work.
> 
> I don't understand other issue. what is different with your custom milk data?
> 
> ![error](https://private-user-images.githubusercontent.com/100773530/300996498-1c9e38de-a30e-43d0-837e-df33425d90d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzQwMjIsIm5iZiI6MTcyNzMzMzcyMiwicGF0aCI6Ii8xMDA3NzM1MzAvMzAwOTk2NDk4LTFjOWUzOGRlLWEzMGUtNDNkMC04MzdlLWRmMzM0MjVkOTBkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNjU1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjg2YjI0NjMwYWUyNzVjYTNlNTllN2MwZTg2ZGM2YWExNjIxYjljZWZhMjIzMjE3ZDM1MmExNjVkM2I3Yjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SKbe_iheNPNkgm8F_04zUX3-jjMs-OK31zsWVFbQc4I)

hello ,how do you solve the problem in the figure below?
![Uploading 图片.png…]()

**Comment by JINAOLONG** [comment]
> Hello!
> 
> Thanks to your great job!
> 
> i try to make a custom data.
> 
> i already made color image, depth image using Orbbec Femto.
> 
> then i make mask image using XMem.
> 
> But, BundleSDF doesn't work.
> 
> I don't understand other issue. what is different with your custom milk data?
> 
> ![error](https://private-user-images.githubusercontent.com/100773530/300996498-1c9e38de-a30e-43d0-837e-df33425d90d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzUwMTMsIm5iZiI6MTcyNzMzNDcxMywicGF0aCI6Ii8xMDA3NzM1MzAvMzAwOTk2NDk4LTFjOWUzOGRlLWEzMGUtNDNkMC04MzdlLWRmMzM0MjVkOTBkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwNzExNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWIwNzUwZmUzMWNhN2Y1MzkzYTUzY2M1OThkNzRmZTBkODljMThkZGUzOWVlYTQ4ZjlmYjZkODU1NDY0NDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F-AyhScUi6r-ws9pq9qHI1H3j9bcmFEyNqTdxT93sKA)

hello,how do you solve the problem in the figure below?
![图片](https://github.com/user-attachments/assets/870286f5-fa9d-49c0-8280-2b341342e43d)

**Comment by MichaelWangGo** [comment]
@lsy-92 Hi bro, how did you make masks for your data? Making a single mask as desribed in authors' paper? Or making mask for each rgb image?

**Comment by wenbowen123** [comment]
the depth does not have to be in [0,1]. You should make sure it's in metric scale.

You can use SAM2 to create masks.
