### ISSUE TITLE
ImportError: libQt5Core.so.5: cannot open shared object : my_cpp

### ISSUE THREAD

**Issue by TakiToolu** [NVlabs/BundleSDF#148]
I have run 'bash build.sh' in the docker container(success build 100%), and can see the file ' my_cpp.cpython-38-x86_64-linux-gnu.so' in path '/Bundletrack/build',but it still show error when I run 
```
"python3 run_custom.py --mode run_video --video_dir /mnt/debug/2022-11-18-15-10-24_milk --out_folder /mnt/debug/bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 1 --debug_level 2"
```
it shows:
```
root@centos:/mnt/code/SDF# python3 run_custom.py --mode run_video --video_dir /mnt/debug/2022-11-18-15-10-24_milk --out_folder /mnt/debug/bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 1 --debug_level 2
code_dir /mnt/code/SDF
Traceback (most recent call last):
  File "run_custom.py", line 10, in <module>
    from bundlesdf import *
  File "/mnt/code/SDF/bundlesdf.py", line 21, in <module>
    from BundleTrack.build import my_cpp
ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory
```

I have tried others ways to solve it ,
- add PYTHONPATH to i ~/.bashrc and source it ,It doesn't work.
- cp my_cpp.cpython-38-x86_64-linux-gnu.so my_cpp.so ,in that path,It  doesn't work .

what else can I do  so solve it ?

**Comment by TakiToolu** [comment]
我重新跑了一遍dockerfile的命令，有的命令是在conda环境中执行的，顺序不能乱，问题解决

**Comment by DI-LEE** [comment]
you can use 

https://github.com/YosysHQ/nextpnr/issues/375
