### ISSUE TITLE
mportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found 

### ISSUE THREAD

**Issue by nuaayxy** [NVlabs/BundleSDF#15]
[2023-06-26 12:54:21.365] [warning] [Bundler.cpp:67] forgetting frame 1668813028470606334
[2023-06-26 12:54:21.365] [warning] [FeatureManager.cpp:469] forgetting frame 1668813028470606334
[bundlesdf.py] exceed window size, forget frame 1668813028470606334
[2023-06-26 12:54:21.366] [warning] [Bundler.cpp:435] total keyframes=4, want to select 10
[2023-06-26 12:54:21.366] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813025164826994 visible=0.875298
[2023-06-26 12:54:21.366] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813025164826994) into pairs
[2023-06-26 12:54:21.366] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813026867024573 visible=0.861925
[2023-06-26 12:54:21.366] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813026867024573) into pairs
[2023-06-26 12:54:21.367] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813028304456241 visible=0.844804
[2023-06-26 12:54:21.367] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813028304456241) into pairs
[2023-06-26 12:54:21.367] [warning] [Bundler.cpp:793] frame 1668813028705557007 and 1668813028571340409 visible=0.87368
[2023-06-26 12:54:21.367] [warning] [Bundler.cpp:802] add frame (1668813028705557007, 1668813028571340409) into pairs
[bundlesdf.py] frame_pairs: 4
[loftr_wrapper.py] image0: torch.Size([4, 1, 400, 400])
[loftr_wrapper.py] net forward
[loftr_wrapper.py] mconf, 0.20005133748054504 0.9916833639144897
[loftr_wrapper.py] pair_ids (1613,)
[loftr_wrapper.py] corres: (1613, 5)
[2023-06-26 12:54:21.533] [warning] [FeatureManager.cpp:1589] start multi pair ransac GPU, pairs#=4
[2023-06-26 12:54:21.544] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813025164826994 #inliers=153, #prev 278
[2023-06-26 12:54:21.544] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813026867024573 #inliers=136, #prev 283
[2023-06-26 12:54:21.544] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813028304456241 #inliers=168, #prev 280
[2023-06-26 12:54:21.544] [warning] [FeatureManager.cpp:1699] ransac makes match betwee frame 1668813028705557007 1668813028571340409 #inliers=355, #prev 457
#optimizeGPU frames=5, #keyframes=4, #_frames=10
1668813025164826994 1668813026867024573 1668813028304456241 1668813028571340409 1668813028705557007 
[2023-06-26 12:54:21.551] [warning] [Bundler.cpp:920] OptimizerGPU begin, global_corres#=2947
global_corres=2947
maxNumResiduals / maxNumberOfImages = 50947 / 5 = 10189
m_maxNumberOfImages*m_maxCorrPerImage = 5 x 1309 = 6545
m_solver->solve Time difference = 9.754[ms]
[2023-06-26 12:54:21.566] [warning] [Bundler.cpp:924] OptimizerGPU finish
[2023-06-26 12:54:21.567] [warning] [Bundler.cpp:320] Added frame 1668813028705557007 as keyframe, current #keyframe: 5
[bundlesdf.py] processNewFrame done 1668813028705557007
[bundlesdf.py] 1668813028705557007 prepare data for nerf
[bundlesdf.py] out_dir: ./output//1668813028705557007/nerf
[tool.py] compute_scene_bounds_worker start
[tool.py] compute_scene_bounds_worker done
[tool.py] merge pcd
[tool.py] compute_translation_scales done
translation_cvcam=[0.00950763 0.00492653 0.0066628 ], sc_factor=8.09038237262584
[bundlesdf.py] First nerf run, create Runner, latest nerf frame 1668813028705557007
[nerf_runner.py] Octree voxel dilate_radius:1
level 0, resolution: 16
level 1, resolution: 32
level 2, resolution: 64
level 3, resolution: 128
GridEncoder: input_dim=3 n_levels=4 level_dim=2 resolution=16 -> 128 per_level_scale=2.0000 params=(2462192, 2) gridtype=hash align_corners=False
sc_factor 5.663267660838088
translation [0.00950763 0.00492653 0.0066628 ]
[nerf_runner.py] denoise cloud
[nerf_runner.py] Denoising rays based on octree cloud
[nerf_runner.py] bad_mask#=443
rays torch.Size([341656, 12])
[bundlesdf.py] Start training, latest nerf frame 1668813028705557007
[nerf_runner.py] train progress 0/501
[nerf_runner.py] Iter: 0, valid_samples: 393216/393216, valid_rays: 2048/2048, loss: 6.2736540, rgb_loss: 3.0207248, rgb0_loss: 0.0000000, fs_rgb_loss: 0.0000000, depth_loss: 0.0000000, depth_loss0: 0.0000000, fs_loss: 0.5849329, point_cloud_loss: 0.0000000, point_cloud_normal_loss: 0.0000000, sdf_loss: 2.6679962, eikonal_loss: 0.0000000, variation_loss: 0.0000000, truncation(meter): 0.0100000, pose_reg: 0.0000000, reg_features: 0.0000000, 

[nerf_runner.py] train progress 50/501
[nerf_runner.py] train progress 100/501
[nerf_runner.py] train progress 150/501
[nerf_runner.py] train progress 200/501
[nerf_runner.py] train progress 250/501
[nerf_runner.py] train progress 300/501
[nerf_runner.py] train progress 350/501
[nerf_runner.py] train progress 400/501
[nerf_runner.py] train progress 450/501
[nerf_runner.py] train progress 500/501
[bundlesdf.py] Training done, latest nerf frame 1668813028705557007
[bundlesdf.py] Getting mesh
[nerf_runner.py] query_pts:torch.Size([357911, 3]), valid:36153
[nerf_runner.py] Running Marching Cubes
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xye/BundleSDF/bundlesdf.py", line 234, in run_nerf
    mesh = nerf.extract_mesh(isolevel=0,voxel_size=cfg_nerf['mesh_resolution'])
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xye/BundleSDF/nerf_runner.py", line 1389, in extract_mesh
    from skimage import measure
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/lazy_loader/__init__.py", line 73, in __getattr__
    return importlib.import_module(f"{package_name}.{name}")
  File "/opt/conda/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/skimage/measure/__init__.py", line 5, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/skimage/measure/_polygon.py", line 2, in <module>
    from scipy import signal
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/signal/__init__.py", line 309, in <module>
    from . import _sigtools, windows
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/signal/windows/__init__.py", line 41, in <module>
    from ._windows import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/signal/windows/_windows.py", line 7, in <module>
    from scipy import linalg, special, fft as sp_fft
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/fft/__init__.py", line 91, in <module>
    from ._helper import next_fast_len
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/fft/_helper.py", line 3, in <module>
    from ._pocketfft import helper as _helper
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/fft/_pocketfft/__init__.py", line 3, in <module>
    from .basic import *
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/scipy/fft/_pocketfft/basic.py", line 6, in <module>
    from . import pypocketfft as pfft
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/envs/py38/lib/python3.8/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-38-x86_64-linux-gnu.so)
^CTraceback (most recent call last):

**Comment by monajalal** [comment]
https://github.com/NVlabs/BundleSDF/issues/2

**Comment by redgreenblue3** [comment]
In short, by following issue #2, I got the following solution that should work out of the box:

```
conda install -c conda-forge gcc=12.1.0
cp /opt/conda/envs/py38/lib/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/
rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
```

You might have to change ```libstdc++.so.6.0.31``` to whatever ```libstdc++.so.6.0.xx``` you have in ```/opt/conda/envs/py38/lib/```, ideally the latest one (highest ```xx``` suffix).

----------------------------------

In case you want to reproduce my setup, here is what I did to get this repo to run overall:
```
# Start docker container
docker rm -f bundlesdf
docker run --gpus all --env NVIDIA_DISABLE_REQUIRE=1 -it --network=host --name bundlesdf  --cap-add=SYS_PTRACE --security-opt seccomp=unconfined  -v /home:/home -v /tmp:/tmp -v /mnt:/mnt -v $DIR:$DIR  --ipc=host -e DISPLAY=${DISPLAY} -e GIT_INDEX_FILE nvcr.io/nvidian/bundlesdf:latest bash

# In container, build remaining dependencies
cd /home/myuser/BundleSDF
bash build.sh

# Solve GLIBCXX error
conda install -c conda-forge gcc=12.1.0
cp /opt/conda/envs/py38/lib/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/
rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/libstdc++.so.6

# Test
python run_custom.py --mode run_video --video_dir /home/myuser/BundleSDF/milk/2022-11-18-15-10-24_milk --out_folder /home/myuser/BundleSDF/milk/out_stage1 --use_segmenter 1 --use_gui 0 --debug_level 2
```
I am running in a setup where I don't have access to a gui, therefore ```--use_gui 0```.

**Comment by nuaayxy** [comment]
> In short, by following issue #2, I got the following solution that should work out of the box:
> 
> ```
> conda install -c conda-forge gcc=12.1.0
> cp /opt/conda/envs/py38/lib/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/
> rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> ```
> 
> You might have to change `libstdc++.so.6.0.31` to whatever `libstdc++.so.6.0.xx` you have in `/opt/conda/envs/py38/lib/`, ideally the latest one (highest `xx` suffix).
> 
> In case you want to reproduce my setup, here is what I did to get this repo to run overall:
> 
> ```
> # Start docker container
> docker rm -f bundlesdf
> docker run --gpus all --env NVIDIA_DISABLE_REQUIRE=1 -it --network=host --name bundlesdf  --cap-add=SYS_PTRACE --security-opt seccomp=unconfined  -v /home:/home -v /tmp:/tmp -v /mnt:/mnt -v $DIR:$DIR  --ipc=host -e DISPLAY=${DISPLAY} -e GIT_INDEX_FILE nvcr.io/nvidian/bundlesdf:latest bash
> 
> # In container, build remaining dependencies
> cd /home/myuser/BundleSDF
> bash build.sh
> 
> # Solve GLIBCXX error
> conda install -c conda-forge gcc=12.1.0
> cp /opt/conda/envs/py38/lib/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/
> rm /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.31 /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> 
> # Test
> python run_custom.py --mode run_video --video_dir /home/myuser/BundleSDF/milk/2022-11-18-15-10-24_milk --out_folder /home/myuser/BundleSDF/milk/out_stage1 --use_segmenter 1 --use_gui 0 --debug_level 2
> ```
> 
> I am running in a setup where I don't have access to a gui, therefore `--use_gui 0`.

great that works

**Comment by nuaayxy** [comment]
Finally it runs, now the milk dataset takes about 3 hours on my 3080, does that sounds normal

**Comment by redgreenblue3** [comment]
> Finally it runs, now the milk dataset takes about 3 hours on my 3080, does that sounds normal

Yes, that does sound normal - I can't give you an exact comparison because I am running on an RTX A5000 and haven't run the complete milk dataset yet, but it generally seems to take long for me, on the order of hours.

You can get some preliminary results by processing less frames, possibly also with a bigger stride (skip some frames in between), by adjusting ```run_custom.py``` (lines 68-77 here) like follows:

```
  tracker = BundleSdf(cfg_track_dir=cfg_track_dir, cfg_nerf_dir=cfg_nerf_dir, start_nerf_keyframes=5, use_gui=use_gui)

  reader = YcbineoatReader(video_dir=video_dir, shorter_side=480)

  args.stride = 5 # Adjusts stride (can be done more elegantly)

  n_considered_frames = 500 # Adjust to process more / less frames. Actual number of processed frames depends on stride.


  for i in range(0, n_considered_frames, args.stride):
    color_file = reader.color_files[i]
    color = cv2.imread(color_file)
    H0, W0 = color.shape[:2]
    depth = reader.get_depth(i)
```

**Comment by monajalal** [comment]
@redgreenblue3 thanks a lot for the insight. Any chance you may have faced this error or you may know how to fix it? I get it on both local machine with RTX 3080 mobile and azure compute instance with two V100 GPUs.

```
(py38) root@bundlesdf:/home/azureuser/BundleSDF# time python run_custom.py --mode run_video --video_dir /home/azureuser/BundleSDF/milk/2022-11-18-15-10-24_milk  --out_folder /home/azureuser/BundleSDF/milk/out --use_segmenter 1 --use_gui 0 --debug_level 2


level 7, resolution: 59
level 8, resolution: 71
level 9, resolution: 85
level 10, resolution: 102
level 11, resolution: 123
level 12, resolution: 148
level 13, resolution: 177
level 14, resolution: 213
level 15, resolution: 256
GridEncoder: input_dim=3 n_levels=16 level_dim=2 resolution=16 -> 256 per_level_scale=1.2030 params=(20411696, 2) gridtype=hash align_corners=False
sc_factor 5.770792362607293
translation [0.01209092 0.00797227 0.01039174]
[nerf_runner.py] denoise cloud
[nerf_runner.py] Denoising rays based on octree cloud
[nerf_runner.py] bad_mask#=85777
rays torch.Size([5709983, 12])
Start training
[nerf_runner.py] train progress 0/2001
[nerf_runner.py] Iter: 0, valid_samples: 655076/655360, valid_rays: 2048/2048, loss: 14.0785551, rgb_loss: 11.9679470, rgb0_loss: 0.0000000, fs_rgb_loss: 0.0000000, depth_loss: 0.0000000, depth_loss0: 0.0000000, fs_loss: 0.0753194, point_cloud_loss: 0.0000000, point_cloud_normal_loss: 0.0000000, sdf_loss: 1.9268247, eikonal_loss: 0.0000000, variation_loss: 0.0000000, truncation(meter): 0.0100000, pose_reg: 0.0000000, reg_features: 0.1084646, 

[nerf_runner.py] train progress 200/2001
[nerf_runner.py] train progress 400/2001
[nerf_runner.py] train progress 600/2001
[nerf_runner.py] train progress 800/2001
[nerf_runner.py] train progress 1000/2001
[nerf_runner.py] train progress 1200/2001
[nerf_runner.py] train progress 1400/2001
[nerf_runner.py] train progress 1600/2001
[nerf_runner.py] train progress 1800/2001
[nerf_runner.py] train progress 2000/2001
cp: cannot stat '/home/azureuser/BundleSDF/milk/out//nerf_with_bundletrack_online/image_step_*.png': No such file or directory
[nerf_runner.py] query_pts:torch.Size([5177717, 3]), valid:1255018
[nerf_runner.py] Running Marching Cubes
[nerf_runner.py] done V:(82217, 3), F:(163824, 3)
[acceleratesupport.py] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[A^[[A^[[A^[[A^[[A^CProcess Process-4:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/azureuser/BundleSDF/bundlesdf.py", line 128, in run_nerf
    time.sleep(0.01)
KeyboardInterrupt
^Z
[2]+  Stopped                 python run_custom.py --mode run_video --video_dir /home/azureuser/BundleSDF/milk/2022-11-18-15-10-24_milk --out_folder /home/azureuser/BundleSDF/milk/out --use_segmenter 1 --use_gui 0 --debug_level 2

real    13m28.506s
user    0m0.000s
sys     0m0.000s
```

I ran it with your suggested changes for faster debugging
```
args.stride = 5 # Adjusts stride (can be done more elegantly)

n_considered_frames = 500 # Adjust to process more / less frames. Actual number of processed frames depends on stride.
```

**Comment by monajalal** [comment]
@redgreenblue3 when I ran with less images exactly with the setting you suggested, I got this error when opening the `textured_mesh.obj` with MeshLab. Did you have the same problem?

Please let me know if you may have any suggestion?
```
(base) mona@ard-gpu-01:~/milk/out_small$ meshlab
Current Plugins Dir is: /usr/lib/x86_64-linux-gnu/meshlab/plugins 
Shader directory found '/usr/share/meshlab/shaders', and it contains 19 gdp files
meshlab: ./vcglib/wrap/io_trimesh/import_obj.h:640: static int vcg::tri::io::ImporterOBJ<OpenMeshType>::Open(OpenMeshType&, const char*, vcg::tri::io::ImporterOBJ<OpenMeshType>::Info&) [with OpenMeshType = CMeshO]: Assertion `(numTriangles +numVertices) == numVerticesPlusFaces+extraTriangles' failed.
Aborted (core dumped)
```

**Comment by redgreenblue3** [comment]
@monajalal I only tried mesh_cleaned.obj, which worked. Haven't tried textured_mesh.obj yet.

**Comment by monajalal** [comment]
@redgreenblue3 thanks a lot for confirming. It worked in Blender (even that one throws error in Meshlab).

Glad it is working. Thank you.
![Screenshot from 2023-06-28 14-16-12](https://github.com/NVlabs/BundleSDF/assets/1892917/4e4aed08-7ec9-4aee-87e5-a1b00c65f2ae)

**Comment by lunalulu** [comment]
May I ask if you have encountered this problem?
when run run_one_video_global_nerf
![image](https://github.com/NVlabs/BundleSDF/assets/40664601/e263d052-5886-4ef0-9972-9d77394075ad)

**Comment by lunalulu** [comment]
I downgrading to pyrender==0.1.31, but i have another error
![image](https://github.com/NVlabs/BundleSDF/assets/40664601/915392ad-85f1-4818-a11e-90d8dbda9e7f)

and my apt dont work

**Comment by redgreenblue3** [comment]
@lunalulu Have you tried running it without the gui, i.e.  `--use_gui 0` ?

**Comment by monajalal** [comment]
@lunalulu did you install this?
`pip install PyOpenGL-accelerate`

**Comment by lunalulu** [comment]
> @lunalulu Have you tried running it without the gui, i.e. `--use_gui 0` ?

yes that's what i do

**Comment by lunalulu** [comment]
> @lunalulu did you install this? `pip install PyOpenGL-accelerate`

Thanks, I have followed this link, but still have errors

**Comment by lunalulu** [comment]
Now I have successfully executed the first step，and when i run
`python run_custom.py --mode get_mesh --video_dir /home/bowen/debug/2022-11-18-15-10-24_milk --out_folder /home/bowen/debug/bundlesdf_2022-11-18-15-10-24_milk`

i got errors, i dont have any *normalized_space.obj

Do you encounter this problem?thanks
@monajalal @redgreenblue3 @nuaayxy

**Comment by monajalal** [comment]
@lunalulu yes I have the same issue. Please check https://github.com/NVlabs/BundleSDF/issues/24

**Comment by lunalulu** [comment]
> @lunalulu yes I have the same issue. Please check #24

I understand that it cannot be saved because of the setting of i_mesh equal np.inf， So how do I set this parameter？？
thanks~

**Comment by Tsianmy** [comment]
> May I ask if you have encountered this problem? when run run_one_video_global_nerf ![image](https://user-images.githubusercontent.com/40664601/249738324-e263d052-5886-4ef0-9972-9d77394075ad.png)

@lunalulu May I ask how did you fix this error? I have the same problem when running `run_one_video_global_nerf`.

```
[nerf_runner.py] Running Marching Cubes      
[nerf_runner.py] done V:(90796, 3), F:(181210, 3)                       
[acceleratesupport.py] OpenGL_accelerate module loaded
[arraydatatype.py] Using accelerated ArrayDatatype
Traceback (most recent call last):                                                               
  File "run_custom.py", line 225, in <module>
    run_one_video_global_nerf(out_folder=args.out_folder)                                   
  File "run_custom.py", line 152, in run_one_video_global_nerf
    tracker.run_global_nerf(reader=reader, get_texture=True, tex_res=512)                          
  File "/home/zhouqi/repos/BundleSDF/bundlesdf.py", line 763, in run_global_nerf
    mesh = nerf.mesh_texture_from_train_images(mesh, rgbs_raw=rgbs_raw, train_texture=False, tex_res=tex_res)
  File "/home/zhouqi/repos/BundleSDF/nerf_runner.py", line 1490, in mesh_texture_from_train_images
    renderer = ModelRendererOffscreen([], cam_K=self.K, H=self.H, W=self.W, zfar=self.cfg['far']*self.cfg['sc_facto
r'])                                                           
  File "/home/zhouqi/repos/BundleSDF/offscreen_renderer.py", line 59, in __init__
    self.r = pyrender.OffscreenRenderer(self.W, self.H)  #!NOTE version>0.1.32 not work https://github.com/mmatl/py
render/issues/85
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/offscreen.py", line 137, in _create
    egl_device = egl.get_device_by_index(device_id)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/pyrender/platforms/egl.py", line 83, in get_device_by_inde
x
    raise ValueError('Invalid device ID ({})'.format(device_id, len(devices)))
ValueError: Invalid device ID (0)
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
 ...
```

**Comment by zhujingsong** [comment]
> May I ask if you have encountered this problem? when run run_one_video_global_nerf ![image](https://private-user-images.githubusercontent.com/40664601/249738324-e263d052-5886-4ef0-9972-9d77394075ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNDUwNzksIm5iZiI6MTcxNTA0NDc3OSwicGF0aCI6Ii80MDY2NDYwMS8yNDk3MzgzMjQtZTI2M2QwNTItNTg4Ni00ZWYwLTk5NzItOWQ3NzM5NDA3NWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDAxMTkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzODA4NDVjZTM5NzU2MmIwM2Q3ZTMzYjU3MTFmNWFmYjU0NDVhYWE4NmZkMDYzNDkyYWJiMTYzYzMzNjU4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.swZyz2xAlMYPpxBv-wO6SY0FfGA06kQ-H120szfzTcE)

SAME. How do you solve this problem?
