### ISSUE TITLE
error running run_custom.py on milk dataset.

### ISSUE THREAD

**Issue by zahid990170** [NVlabs/BundleSDF#151]
I made a first test using the milk dataset and issue the following command. I am running this remotely on a GPU based machine. 

`python run_custom.py --mode run_video --video_dir 2022-11-18-15-10-24_milk --out_folder bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 0 --debug_level 2`

what kind of output shall we get?
do we also receive the pose information? 

after running for a while, the program terminates with this error: 

![image](https://github.com/NVlabs/BundleSDF/assets/56445034/8fc1f1ef-a5be-4cff-a6b5-188e32a3b71f)

There are further optional commands to see further information. 

`python run_custom.py --mode draw_pose --out_folder bundlesdf_2022-11-18-15-10-24_milk `

questions: 

Does `"draw_pose"` expects that first command was already executed.  I received the following error upon executing this: 

**`ValueError: string is not a file: bundlesdf__2022-11-18-15-10-24_milk/textured_mesh.obj`**

Any input or pointers?

thanks,

**Comment by wenbowen123** [comment]
1. Do you have GPU on the machine?
2. If so, did you install nvidia-docker? https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by zahid990170** [comment]
@wenbowen123 

- I have GPU on machine where I am running bundleSDF code. 

![image](https://github.com/NVlabs/BundleSDF/assets/56445034/b5990efb-55ff-4ec4-abba-3a8cd264b912)

![image](https://github.com/NVlabs/BundleSDF/assets/56445034/afbd65a6-8135-46ea-b73c-2896d9da4ffe)

- I installed docker, but not nvidia-docker. I will try installing that. 

thanks your inputs.

**Comment by zahid990170** [comment]
I have re-installed nvidia docker. After running for a while, the program terminates with this error:

`**ModuleNotFoundError: No module named 'gridencoder'**
`

**Comment by athnzc** [comment]
@zahid990170 Did you run the `build.sh` script inside the container?

**Comment by zahid990170** [comment]
@athnzc I had missed this step. I did this, and then the program was running. 
The program runs for a good while but then it terminates with the message that I put in my first post. 

`connection reset by peer`

On the gui, I can see this kind of output

![ss](https://github.com/NVlabs/BundleSDF/assets/56445034/f4b0fa9e-7d3d-41da-a223-71f51174e5a9)


So, it seems that it did not complete. 

In the output folder, there is a lot of data / sub-folders that are generated. 

1668813025164826994
...
...
...
color_segmented
color_viz
depth
depth_filtered
mask
normal
...

I am trying to make a sense of it. Also, I cannot run the other command where `--mode draw_pose`

**Comment by zahid990170** [comment]
some updates: 

I just issued the second command 

`python run_custom.py --mode global_refine `

and passing the arguments, in particular
```
video_dir
out_folder

```
--out_folder is the one output by the first command. 

and, see if it works (out_folder probably is not complete). It worked ok !!

When I issued the last command
` python run_custom.py --mode draw_pose`

`pose_vis `folder contains the images with bounding boxes drawn around the milk box. 

some comments and questions: 

- The visually bounding boxes look off (not very tight) at times. 
- Is there any associated text file for each of these bounding boxes where one can see the pose information (translation and rotation)
- This pose information when available is in which reference frame?

**Comment by wenbowen123** [comment]
1. The first command is most critical and yes it will be used by second and third, which are optional.
2. It will automatically correct the intermediate error later on
3. The pose results will be saved to the out_folder. 
4. The first frame's pose is identity (translation maybe the center of the mesh), the subsequent poses will be relative to the first timestamp.

**Comment by themozel** [comment]
I have the same issue.
Is there a solution there to get rid of the error ?
"[Errno 104] Connection reset by peer"

I have read all the comments but there is no mentions of why this is happening or where does it come from or what the solution might be.

I would appreciate any tips.
