### ISSUE TITLE
run_custom.py stops executing after processing a few images in BundleSDF Docker environment

### ISSUE THREAD

**Issue by Sar-thak-3** [NVlabs/BundleSDF#154]
## Description:
When running the `run_custom.py` script within the BundleSDF Docker environment using the appropriate command, the program encounters an issue where it halts execution after processing a few images without completing its task. 

Command:- `python /mnt/sda4/bundlesdf/BundleSDF/run_custom.py --mode run_video --video_dir /mnt/sda4/bundlesdf/BundleSDF/dataset/pcb --out_folder /mnt/sda4/bundlesdf/BundleSDF/dataset/pcb/out --debug_level 2`

[error.log](https://github.com/NVlabs/BundleSDF/files/15278250/error.log)

**Comment by shirokalu** [comment]
Hello bro, have you solved this problem? I encountered the same issue as you.

**Comment by Sar-thak-3** [comment]
If `error.log` is same for you then
1. Comment this line
https://github.com/NVlabs/BundleSDF/blob/77b28c86b7b27a2abb4398b86dc5ef62b8e4034c/bundlesdf.py#L451
2. Ensure the shape of rgb, depth, mask is same
