### ISSUE TITLE
GPU requirements to run Bundle SDF

### ISSUE THREAD

**Issue by KennethEladistu** [NVlabs/BundleSDF#155]
Hello, May I ask if my Laptop with GTX 1650 I5 can run Bundle SDF git hub code?

**Comment by athnzc** [comment]
Hello, your specs are not sufficient unfortunately. Check this thread here for the requirements: [https://github.com/NVlabs/BundleSDF/issues/18](https://github.com/NVlabs/BundleSDF/issues/18)
