### ISSUE TITLE
Computer crashes after running custom.py

### ISSUE THREAD

**Issue by cwchenwang** [NVlabs/BundleSDF#160]
I tried to set up the docker and run the run_custom.py on the provided milk data with use_gui 0. However, after some running, the code crashes at some point. Since it crashes at the midpoint, I cannot tell which line of the code causes the problem. The log folder contains the following:

![image](https://github.com/NVlabs/BundleSDF/assets/23579918/4547d0fb-01e1-42f9-86bd-14281fd94093)

It seems that the final folder is empty but intermediate results are available.

**Comment by wenbowen123** [comment]
did you monitor your memory usage? It maybe because of OOM.
