### ISSUE TITLE
Unable to build docker

### ISSUE THREAD

**Issue by crsiper** [NVlabs/BundleSDF#165]
Thank you for your impressive work. I attempt to use this repository for object pose estimation.

I have downloaded and installed the docker desktop on my Ubuntu 20.04, however when i run the command: `docker build --network host -t nvcr.io/nvidian/bundlesdf .`, it failed to load metadata. 

The error in the terminal and the docker desktop suggests as below. Could you point out what problem is that?
![Screenshot from 2024-08-13 14-22-24](https://github.com/user-attachments/assets/63f1a34c-cc18-4931-bec5-0f069b95ff1d)
![Screenshot from 2024-08-13 14-21-46](https://github.com/user-attachments/assets/65d3ceef-7914-4df3-a130-3ddb12ceace0)

**Comment by yiqiaoqingyuyu** [comment]
Hello, I have encountered the same issue. Have you resolved it?
