### ISSUE TITLE
The output texture image by offical data(milk) is incorrect.

### ISSUE THREAD

**Issue by y200504040u** [NVlabs/BundleSDF#167]
I downloaded the offical data for milk. According to the documentation, I ran run_custom.py in both mode run_video and mode global_refine, and obtained textured_mesh.obj and texture.png. However, the generated texture image seems to have some issues, as shown in the image below:

![20240906-150808](https://github.com/user-attachments/assets/7e81d167-a0ae-4af1-81ed-783168609e90)

Could you please help identify where the problem might be?

**Comment by wenbowen123** [comment]
Hi, the texture generation is an add-on feature beyond the paper. So it was not well optimized and supported.

**Comment by y200504040u** [comment]
> Hi, the texture generation is an add-on feature beyond the paper. So it was not well optimized and supported.

I got it. Thanks a lot!
