### ISSUE TITLE
Mesh generation of a moving  vehicle at every frame of the video sequence recorded from another moving object

### ISSUE THREAD

**Issue by Tuhin-nd** [NVlabs/BundleSDF#169]
哥儿 @wing-kit @wenbowen123,  Awesome work indeed! 

I have few questions, would highly appreciate your response -

* Will BundleSDF be able to properly built mesh representations of the object at every instance of the video?

* Scene: Both camera (ego vehicle) and some other target vehicle are moving. Maximum distance of the target vehicle can be at most 50 metres. I gave the segmentation masks of the target vehicle along with rgb and depth as input - will BundleSDF be able to produce mesh of the object at each frame with correct pose and orientation 6D?

**Comment by wenbowen123** [comment]
- if you have RGBD and instance masks for each of them, then it should be feasible
- Again, if you have depth and masks, it should be feasible. But since this is a driving scene, there are some params that need to be adapted such as farthest depth clipping.
