### ISSUE TITLE
Reconstruct the object with black part

### ISSUE THREAD

**Issue by EAST-J** [NVlabs/BundleSDF#170]
Hi, the project page displays the reconstruction result of the drill. However, when I attempt to reconstruct the drill using the HO3D data (as shown below), the black part appears incomplete. How can I achieve the same results as shown on the project page?
![image](https://github.com/user-attachments/assets/902197c0-2a02-4d93-ae96-e363b47bfc3b)
![image](https://github.com/user-attachments/assets/89fffbb6-61b9-44af-a9d5-01661cea3065)

**Comment by EAST-J** [comment]
Is this because of the incomplete depth image of the black part?

**Comment by wenbowen123** [comment]
> Is this because of the incomplete depth image of the black part?

it is possible. Did you visualize per frame point cloud? Do they have points around the black regions?
