### ISSUE TITLE
cam_K.txt里的数据是什么函意，怎么得到的，谢谢

### ISSUE THREAD

**Issue by paul007008** [NVlabs/BundleSDF#20]

**Comment by paul007008** [comment]
牛奶是哪个数据集，制作流程都有哪些

**Comment by wenbowen123** [comment]
cam_K is camera intrinsics. They are usually available from RGBD camera if you are using Kinect, Realsense, etc
Milk is our own captured data just as an example if you want to run on your own captured ones.
