### ISSUE TITLE
run 2022-11-18-15-10-24_milk example error?

### ISSUE THREAD

**Issue by lunalulu** [NVlabs/BundleSDF#21]
thanks for your great works!

when i run script below
`python run_custom.py --mode run_video --video_dir /home/bowen/debug/2022-11-18-15-10-24_milk --out_folder /home/bowen/debug/bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 1 --debug_level 2`
at last, it happen:
![image](https://github.com/NVlabs/BundleSDF/assets/40664601/340ad0e1-cb37-4c78-8e59-587b8027334a)

i dont have any other errors~

**Comment by lunalulu** [comment]
my GPU is RTX 3090
32G  Memory

**Comment by wenbowen123** [comment]
this seems like it's running out of memory. Can you monitor your mem usage when running? If that's the issue, you can try reducing the image resolutions

**Comment by lunalulu** [comment]
OK，thank you very much！
i will try later
---- Replied Message ----
| From | Bowen ***@***.***> |
| Date | 06/29/2023 07:37 |
| To | NVlabs/BundleSDF ***@***.***> |
| Cc | lunalulu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [NVlabs/BundleSDF] run 2022-11-18-15-10-24_milk example error? (Issue #21) |

this seems like it's running out of memory. Can you monitor your mem usage when running? If that's the issue, you can try reducing the image resolutions

**Comment by monajalal** [comment]
@lunalulu 
use tmux with multi panels and use the following commands in the other two:
$ tiptop (or btop)
$ nvtop
