### ISSUE TITLE
Debugging C++ code pieces

### ISSUE THREAD

**Issue by redgreenblue3** [NVlabs/BundleSDF#23]
How can we print / log for debugging purposes in those parts of the code that are written in C++?

Specifically, I ran into the following error message (trying on different data than the milk example):
```
[pcl::PLYWriter::writeASCII] Input point cloud has no data!
[pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
[pcl::PLYWriter::writeASCII] Input point cloud has no data!
```

which I narrowed down to line 406 in `bundlesdf.py`:
```
def process_new_frame(self, frame):
  frame.invalidatePixelsByMask(frame._fg_mask)

  ...

      if frame._id==0 and np.abs(np.array(frame._pose_in_model)-np.eye(4)).max()<=1e-4:
l.406    frame.setNewInitCoordinate()
```

From what I understand, this function in turn is written in C++ in `BundleSDF/BundleTrack/src/Frame.cpp`:
```
void Frame::setNewInitCoordinate()
{
  const std::string debug_dir = (*yml)["debug_dir"].as<std::string>();
  PointCloudRGBNormal::Ptr cloud(new PointCloudRGBNormal);
  for (int w=0;w<_W;w++)
...
```

To see what's happening here, I have tried both 
`py::print("My debugging text");` and `std::cout << "My debugging text" << std::endl;`, but neither are printed in the console when running `run_custom.py`. I set the debugging level to 3.

So: How do I pass messages from those C++ bits to the console for debugging?

**Comment by wenbowen123** [comment]
after changing the c++ code, you need to rebuild (e.g. `bash build.sh`). Have you tried that?

**Comment by redgreenblue3** [comment]
True, that was the problem, thanks.

I guess just running
 `cd BundleTrack && rm -rf build && mkdir build && cd build && cmake .. && make -j11`
 does the job.
