### ISSUE TITLE
[Feature Request/Brainstorming] Can Segment Anything (SAM) be used in place of XMEM?

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#25]
If SAM can be used in place of XMEM, should we follow a certain format? Have you tried using SAM results instead of XMEM by any chance?

**Comment by wenbowen123** [comment]
Yes, we've tried using SAM to provide an initial mask and it works well. If you want to use SAM to get the per-frame mask, that probably also works.
