### ISSUE TITLE
How To Show Axis-aligned Bounding Box 

### ISSUE THREAD

**Issue by paul007008** [NVlabs/BundleSDF#26]
May I ask where you can find the code to display the bounding box; What steps can be taken to achieve this

**Comment by wenbowen123** [comment]
In the output_dir, there is a `ob_in_cam` folder which stores the tracked object poses. You can project a 3D cuboid using that pose for viz. To get axis-aligned, you can rotate the reconstructed mesh to the axis you want to align (e.g. Z up). Then multiply that rotation transformation to the tracked poses.
