### ISSUE TITLE
error run python run_custom.py --mode get_mesh??

### ISSUE THREAD

**Issue by lunalulu** [NVlabs/BundleSDF#28]
After I execute the first command
`python run_custom.py --mode run_video --video_dir /home/bowen/debug/2022-11-18-15-10-24_milk --out_folder /home/bowen/debug/bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 0 --debug_level 2`
I execute the second
`python run_custom.py --mode get_mesh --video_dir /home/bowen/debug/2022-11-18-15-10-24_milk --out_folder /home/bowen/debug/bundlesdf_2022-11-18-15-10-24_milk`

and i got this：
![image](https://github.com/NVlabs/BundleSDF/assets/40664601/e293b95f-e793-4cc3-afd0-b1747edbe9e5)

Looks like I'm missing something~

thanks

**Comment by wenbowen123** [comment]
In your output dir, can you verify if you already have the obj file of the mesh?

**Comment by redgreenblue3** [comment]
I have the same issue. After running both stages 1 and 2, I seem to have no `normalized_space.obj` files.
```
BundleSDF/data/SM1_processed/out_stage1# find . -name "*.obj"
./0340/nerf/mesh_real_world.obj
./0300/nerf/mesh_real_world.obj
./0460/nerf/mesh_real_world.obj
./0260/nerf/mesh_real_world.obj
./0220/nerf/mesh_real_world.obj
./0440/nerf/mesh_real_world.obj
./0380/nerf/mesh_real_world.obj
./mesh_cleaned.obj
./0240/nerf/mesh_real_world.obj
./textured_mesh.obj
./0420/nerf/mesh_real_world.obj
./0480/nerf/mesh_real_world.obj
```

For reference, I ran:
Stage 1:
```python run_custom.py --mode run_video --video_dir BundleSDF/data/SM1_processed/ --out_folder BundleSDF/data/SM1_processed/out_stage1 --use_segmenter 1 --use_gui 0 --debug_level 2 --stride 20```

Stage 2:
```python run_custom.py --mode global_refine --video_dir BundleSDF/data/SM1_processed/ --out_folder BundleSDF/data/SM1_processed/out_stage1/```

Stage 3:
```python run_custom.py --mode get_mesh --video_dir BundleSDF/data/SM1_processed/ --out_folder BundleSDF/data/SM1_processed/out_stage1/```

**Comment by lunalulu** [comment]
@redgreenblue3 i modify config ，now i can run correctly
![image](https://github.com/NVlabs/BundleSDF/assets/40664601/60d32dce-fd8c-4d3b-9cd6-daf97158c172)

![image](https://github.com/NVlabs/BundleSDF/assets/40664601/88b02764-7f13-4f9c-8bf6-315cd8d502cd)

but, i dont makesure about that~

**Comment by wenbowen123** [comment]
Stage 3 is deprecated and optional. After stage2, you should have a obj file in the output dir already.

**Comment by monajalal** [comment]
@redgreenblue3 and @wenbowen123 
so, are we not expected to have the following file created by any of the steps?
normalized_space.obj
