### ISSUE TITLE
ERROR: failed to solve: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04: docker.io/nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04: not found 

### ISSUE THREAD

**Issue by jaswu51** [NVlabs/BundleSDF#30]

**Comment by yuan-thomas** [comment]
I have successfully built the image using instead 11.3.1.

**Comment by yuan-thomas** [comment]
I have successfully built the image using instead 11.3.1.

**Comment by yuan-thomas** [comment]
Seems 11.3.1 should work.

**Comment by yu-james** [comment]
11.3.1 should work.

**Comment by jaswu51** [comment]
> Modify Dockerfile. 11.3.1 should work.

thank you, I tried 'FROM nvidia/cuda:11.4.3-cudnn8-devel-ubuntu20.04', and it works as well

**Comment by HeyDavid633** [comment]
Thank you very much for this **notification**!
