### ISSUE TITLE
Failed to pull docker image. "authentication required"

### ISSUE THREAD

**Issue by StarRealMan** [NVlabs/BundleSDF#33]
Thank you for providing such nice work!

When I tried to run the implementation on my computer, I encountered the error below:
> sudo docker pull nvcr.io/nvidian/bundlesdf
> Using default tag: latest
> Error response from daemon: unauthorized: authentication required

However, I can pull from dockerhub as usual. So I guess it is because of the poor network.
Could you please publish the image on dockerhub? This will help a lot. Thank you again.

**Comment by lwcode** [comment]
with the same problem

**Comment by redgreenblue3** [comment]
See issue #1. I think the solution is building from scratch (option 2 on the environment setup section of the README). In the BundleSDF directory, do:

```
cd docker
docker build --network host -t nvcr.io/nvidian/bundlesdf .
```

**Comment by StarRealMan** [comment]
Thank you for the suggestion. Sorry I didn't check the closed issues.
I have tried building from scratch using:

> cd docker
> docker build --network host -t nvcr.io/nvidian/bundlesdf .

However, I failed to find nvidia/cuda maybe due to the poor internet:

>  => ERROR [internal] load metadata for docker.io/nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04                           1.1s
> ERROR: failed to solve: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04: docker.io/nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04: not found

Can someone help me?

**Comment by StarRealMan** [comment]
I finally figured it out.
The base image used in this project is

> nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04

However, I couldn't find it on dockerhub, so I changed it to 

> nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04

Then, the error is solved.

Chinese users can also change the apt source by adding:

> RUN sed -i s/archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list && \
>          sed -i s/security.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list

before apt operation to prevent network errors.

**Comment by flyflag22** [comment]
docker build --network host -t nvcr.io/nvidian/bundlesdf 
ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build
Thank you for providing such nice work!，but I need to save the problems,Thank you!

**Comment by oliviaylee** [comment]
I am also getting this error despite building from scratch with no errors. What could be the problem?
