### ISSUE TITLE
How is the mask generated in the dataset used in the Bundle SDF project? Thank you

### ISSUE THREAD

**Issue by paul007008** [NVlabs/BundleSDF#35]
How is the mask generated in the dataset used in the Bundle SDF project? Thank you

**Comment by monajalal** [comment]
use xmem interactive_demo.py 
https://github.com/hkchengrex/XMem/blob/main/docs/DEMO.md

**Comment by wang-shuaikang** [comment]
> 使用 xmem Interactive_demo.py [https://github.com/hk Chengrex/XMem/blob/main/docs/DEMO.md](https://github.com/hkchengrex/XMem/blob/main/docs/DEMO.md)

The author of XMem suggested to use eval.py to generate. Based on your experience, which one is easier to use Interactive_demo.py or eval.py?

**Comment by wenbowen123** [comment]
@wang-shuaikang you can use [segment-anything ](https://github.com/facebookresearch/segment-anything)

**Comment by wang-shuaikang** [comment]
> @wang-shuaikang你可以使用[分段任何东西](https://github.com/facebookresearch/segment-anything)

I looked at segmentation anything, it's segmenting the object out, but it doesn't generate a black and white mask, or is there another step

**Comment by wenbowen123** [comment]
@wang-shuaikang  You just need to replace the segmented out foreground object to white, and the rest to be black.

**Comment by wang-shuaikang** [comment]
>Thank you very much for your reply in your busy schedule. Yes, I also just realized that after splitting everything, the object in the foreground after splitting will be replaced with white, and the rest will be black, but I have encountered a problem when splitting anything in this project In the demonstration, it can mark objects with points or boxes, but when I run his amg.py file, it can be automatically generated, but it cannot generate the corresponding mask. It will generate multiple images based on a picture. Many of the multiple masks do not conform to the object, and the corresponding image mask cannot be directly generated. Sir, what code are you using to split anything to get the desired result?

**Comment by wang-shuaikang** [comment]
> @wang-shuaikang 您只需将分割出的前景对象替换为白色，其余的替换为黑色。



> @wang-shuaikang 您只需将分割出的前景对象替换为白色，其余的替换为黑色。

Sir, I used xmem Interactive_demo.py to make a mask for each frame according to @monajalal's method, but the objects in his mask are red, do we have to use a black and white mask, the mask of the red object What is the effect of the code?

> 掩码是 uint8 PNG 文件。您可以通过多种方式获取它，包括 Photoshop、XMem、Mask-RCNN、GrabCut、SAM 等。

**Comment by wenbowen123** [comment]
The red one should also work

**Comment by wang-shuaikang** [comment]
> The red one should also work
Thank you for your reply in spite of your busy schedule, sir, have you tried using other colors of masks, and will it affect the pose estimation?

**Comment by wenbowen123** [comment]
it wont affect, they will either be runnable or not runnable at all

**Comment by wang-shuaikang** [comment]
> 它不会影响，它们要么可运行，要么根本不可运行
Sir is right, I'm sorry for my naive thoughts！！！
