### ISSUE TITLE
Getting errors while running "run_container.sh"

### ISSUE THREAD

**Issue by aarjayparashar** [NVlabs/BundleSDF#39]
![image](https://github.com/NVlabs/BundleSDF/assets/94872130/aed3f4e3-7be4-4519-b4d0-51f84fda57f0)

The docker file was built successfully in my opinion but I run into problems when I start the docker container for the first time using the "bash run_container.sh"
I have attached the error screenshots. 
Specifically, I get:
WSL (7605) errors: CreateProcessEntryCommon:577: execvpe /bin/bash failed 2 

And,

CreateProcessEntryCommon:586: Create process not expected to return

Any help would be appreciated!

**Comment by aarjayparashar** [comment]
Update:
I restarted the PC and tried again and this is what I get now.


Processing fstab with mount -a failed.

<3>WSL (20) ERROR: CreateProcessEntryCommon:370: getpwuid(0) failed 2
<3>WSL (20) ERROR: CreateProcessEntryCommon:374: getpwuid(0) failed 2
<3>WSL (20) ERROR: CreateProcessEntryCommon:577: execvpe /bin/bash failed 2
<3>WSL (20) ERROR: CreateProcessEntryCommon:586: Create process not expected to return+

**Comment by wenbowen123** [comment]
we never tested on Windows. Can you try with Ubuntu?

**Comment by aarjayparashar** [comment]
Hello!
I tried out on Ubuntu but this is what I am getting after building the docker image file and then running:
sudo bash run_container.sh

Error output:

bundlesdf
access control disabled, clients can connect from any host
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:

**Comment by wenbowen123** [comment]
do you have GPU on your machine?

**Comment by wenbowen123** [comment]
also you dont need sudo when running `bash run_container.sh`

**Comment by aarjayparashar** [comment]
Yes, I do have a GPU on my machine (NVIDIA GeForce RTX 3090 Ti).
So, I am sure that the docker installation is correct as I followed the steps as mentioned on the docker documentation and the 'hello_world' image worked!
Then when I use 'docker build --network host -t nvcr.io/nvidian/bundlesdf .', it built the image successfully.
When I the run 'bash run_container.sh', I get the following error message:
'permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock ........'
A quick search told me that this was due to the Docker daemon binding to a Unix socket and by default, it is the 'root' user that owns the Unix socket, and other users can only access it using sudo. (I tried solving this as well by adding the current user to the docker group!)
So, then when I ran the command using 'sudo bash run_container.sh', I get the following error:
bundlesdf
access control disabled, clients can connect from any host
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:

This is where I am stuck right now. It seems my GPU is not getting detected by docker. I am not sure, though! Help would be super appreciated!

**Comment by wenbowen123** [comment]
Did you install nvidia-docker? https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by aarjayparashar** [comment]
Thank you so much! Installing the NVIDIA Container Toolkit solved it!

**Comment by 52THANOS** [comment]
> Did you install nvidia-docker? https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

温博士我在用wsl子系统来打开container后能正常生成容器但无法使用
![image](https://github.com/NVlabs/BundleSDF/assets/117810189/a558cdf6-55c6-488a-b41c-61f380cd17b1)
