### ISSUE TITLE
after ransac, frame has too few matches #1

### ISSUE THREAD

**Issue by kamzero** [NVlabs/BundleSDF#42]
Hi,
I’m trying to run BundleSDF on BEHAVE 30fps dataset. I use run_behave.py script and use config_behave.yml config file.
However, while the object are moving fast, I often encounter the problem that loftr matches are too few after ransac. e.g. sequence Date03_Sub03_boxlarge.2
Is there anything I haven't noticed? Could you please share you hyperparameters of these sequences? 
Thanks for your time and consideration.

**Comment by kamzero** [comment]
![](vscode-remote://ssh-remote%2B10.71.106.250/mnt/nas/share/home/jxr/home/code/BundleSDF/log/Date03_Sub03_boxlarge.2.png)

**Comment by kamzero** [comment]
![image](https://github.com/NVlabs/BundleSDF/assets/40420631/fb20aa84-0058-43d3-9950-7a97915bd689)

**Comment by wenbowen123** [comment]
It is normal that in challenging datasets like BEHAVE, the matches could often be very limited. However, BundleSDF is robust to such scenarios. What if you remove the pdb and continue? Since this is a refactor of the original code, I haven't got a chance to test.

**Comment by kamzero** [comment]
Thank you for your reply. I am trying to continue running after pdb pause. The inaccurate pose estimation caused by failed matches on sequences like Date03_Sub03_chairwood_lift may seriously affect the reconstruction quality. However, on simpler sequences like Date03_Sub3_boxlarge, it seems to have little effect on reconstruction quality (since I have not evaluated the pose estimation yet, I am not sure if the error in pose estimation would significantly increase at such times). 

I have noticed an interesting phenomenon that on the Date03_Sub3_boxlarge sequence, compared to moments of motion blur caused by high-speed translation, match failures seem to occur more frequently when the rotation is larger. I would like to ask which viewpoint you agree with more: that the matching accuracy of loftr is limited and cannot meet the geometric constraints, or that the parameters related to rotation in RANSAC need to be adjusted?

**Comment by wenbowen123** [comment]
>match failures seem to occur more frequently when the rotation is larger

for this I'd suggest to tune the RANSAC parameters first. If there are textures on the objects, loftr usually work well even under large rotations. Also make sure the segmentation quality is not too bad.

**Comment by kamzero** [comment]
![a55fcdad-e471-4373-a82d-2c484b10cf9b](https://github.com/NVlabs/BundleSDF/assets/40420631/f181705a-a568-4673-a41d-30e27dff4c13)
I further analyzed the situation of "few matches after RANSAC" during rotation and found that it was not due to a lack of matches in LOFTR, but rather because few matching points remained after RANSAC. Upon observing several frames of BoxLarge, I found that this often occurred when a face of BoxLarge appeared or disappeared in the camera's field of view due to rotation. This reminded me of the observability problem of rotation angles in visual odometry research. Have you analyzed your algorithm from this perspective?

**Comment by wenbowen123** [comment]
can you elaborate more on the meaning of your viz and the problem you mentioned?
