### ISSUE TITLE
Increasing batchsize is invalid

### ISSUE THREAD

**Issue by y200504040u** [NVlabs/BundleSDF#43]
Thanks for your great works!
I ran run_custom.py on the milk data. I got perfect meshes, and I found a problem that my gpu memory utilization was low, I increased the batchsize by turning up "N_rand" and "netchunk". 
But that didn't work, and my memory-usage maximum was still 6GB+.
I don't know whether my approach was wrong.
Please provide some methods to improve the utilization of gpu memory.
The 2nd question: To speed up convergence, is there an optimal relationship between the values of "n_step", "N_rand", "chunk" and "netchunk" or other setting values?
Looking forward to your answer.
Thanks.

**Comment by wenbowen123** [comment]
it's not suggested to tune these parameters you mentioned. To make more use of GPU you can try, for instance, increasing the number of rays and number of points to be sampled on the rays. About speed convergence, you can try tuning parameters such as learning rates and weights.

**Comment by y200504040u** [comment]
> it's not suggested to tune these parameters you mentioned. To make more use of GPU you can try, for instance, increasing the number of rays and number of points to be sampled on the rays. About speed convergence, you can try tuning parameters such as learning rates and weights.
Is the “number of rays” you mentioned equivalent to "N_rand" I mentioned?
