### ISSUE TITLE
run_one_video_global_nerf() is included in def run_one_video() ?

### ISSUE THREAD

**Issue by y200504040u** [NVlabs/BundleSDF#44]
Thanks for your great works!
https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/run_custom.py#L107
run_one_video_global_nerf() is called by run_one_video()
If run run_custom.py with mode "global_refine" after mode "run_video", run_one_video_global_nerf will be called twice, whether or not it is intended to.
Thanks.

**Comment by wenbowen123** [comment]
you are right that the `run_one_video_global_nerf` will be called in the first stage when jointly track poses and reconstruct. But we still have a separate `run_one_video_global_nerf` that allows running reconstruction only, using the previously tracked poses. This maybe needed in some cases.
