### ISSUE TITLE
Modifying code for real-time tracking

### ISSUE THREAD

**Issue by YoontaeCho** [NVlabs/BundleSDF#45]
Thank you for your amazing work! We are interested at applying your work to robot manipulation, specifically estimating the pose of the object that we're trying to manipulate.
While the uploaded code works well for the custom data, it seems hard to be directly applied since it jointly tracks the object and trains NERF, which causes 5~10 seconds of delay per training. However, as you mentioned at your paper, it's possible to run the online tracker and NERF trainer separately.

<img width="552" alt="Screenshot 2023-07-13 at 4 07 17 PM" src="https://github.com/NVlabs/BundleSDF/assets/118879676/22aeda7b-c094-436a-b13c-c00ea460c30d">

If I want to run only the online tracker but not NERF trainer, to achieve 10hz online tracking speed, could you tell which part of your code that should I disable? Again, thanks for your amazing work!

**Comment by wenbowen123** [comment]
As mentioned in https://github.com/NVlabs/BundleSDF/issues/17, realtime is not supported in this repo. However, disabling nerf could still improve the speed a lot. To do so, you can increase the `start_nerf_keyframes` [here](https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/run_custom.py#L68) to a super large number to disable nerf. Note that the speed might be varying according to the keyframes it was used.
