### ISSUE TITLE
Error encountered - version 'GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by VaibhavSatija10** [NVlabs/BundleSDF#46]
Hi!
After starting the docker container for the first time and running the command for joint tracking and reconstruction, 
**An import error : /lib /x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.29' not found (required by /opt.conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)** is encountered.

On running the command _strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX_, It only lists all the GLIBCXX versions up until GLIBCXX_3.4.28

Thank You
![WhatsApp Image 2023-07-14 at 10 03 51](https://github.com/NVlabs/BundleSDF/assets/89154898/db53bbd9-b380-4c5b-9011-ee024003e0a2)

**Comment by wenbowen123** [comment]
can you try https://github.com/NVlabs/BundleSDF/issues/2 and https://github.com/NVlabs/BundleSDF/issues/15
