### ISSUE TITLE
Is it possible to reconstruct in-the-wild videos?

### ISSUE THREAD

**Issue by linjing7** [NVlabs/BundleSDF#47]
Hi, thanks for your excellent work! 
Is it possible to reconstruct an indoor-scene video without a ground-truth depth map and camera intrinsic parameter? Can I use the estimated depth map and camera intrinsic parameter as the input? If yes, do you have any idea about the recommended networks to estimate accurate depth map and camera intrinsic parameter for indoor scenes?

**Comment by wenbowen123** [comment]
the depth map and intrinsics are from the RGBD camera. We haven't tried using any networks doing so and not sure if this is feasible. If you manage to get the data in some other way than the camera, it should be able to feed to BundleSDF though.
