### ISSUE TITLE
Questions about pose estimation of symmetrical objects

### ISSUE THREAD

**Issue by BoBoINVIDICUS** [NVlabs/BundleSDF#48]
Thanks to your excellent work, we can use a more stable and accurate pose estimation network.
However, when estimating a symmetric object, such as a gear with rotational symmetry, because different angles of view have the same characteristics, the X and Y axes of the coordinate system will be changed repeatedly in the actual estimation process, in other words, the X and Y axes will be changed around the rotation axis, which will lead to a sudden change in the tracking process of the robot arm. How do you solve this problem?

**Comment by BoBoINVIDICUS** [comment]
For example, items in a T-LESS dataset.
![image](https://github.com/NVlabs/BundleSDF/assets/102162738/aa1dd4e5-e41e-4835-9492-25ddf8f6f3b7)

**Comment by wenbowen123** [comment]
BundleSDF tracks the object pose. So if the symmetry is not continuous (say 90deg), it wont affect tracking, since it uses temporal cues. But if the symmetry is continuous (e.g. gear), any one of the symmetry poses are equivalent as long as its vertical axis is right. So it might not matter as well. What's your use case?

**Comment by BoBoINVIDICUS** [comment]
> BundleSDF tracks the object pose. So if the symmetry is not continuous (say 90deg), it wont affect tracking, since it uses temporal cues. But if the symmetry is continuous (e.g. gear), any one of the symmetry poses are equivalent as long as its vertical axis is right. So it might not matter as well. What's your use case?

Thank you for your reply! I read one of your papers :You Only Demonstrate Once, which I am very interested in, so I think I can also do research in this aspect. However, when tracking the pose of the gear, I found that the estimated X and Y axes would transform around the Z axis, which I think should be caused by the rotational symmetry of the gear. Therefore, during the demonstration of assembly, the movement of the robot arm will fluctuate greatly. This is my case, and I sincerely hope that you can give me some advice on how to solve this problem.
