### ISSUE TITLE
Is there a way to save the weight after training and launch inference please?

### ISSUE THREAD

**Issue by assia855** [NVlabs/BundleSDF#51]

**Comment by wenbowen123** [comment]
what do you mean by inference? Similar to NeRF, BundleSDF is traind per scene

**Comment by assia855** [comment]
thanks for your reply @wenbowen123. The training takes a long  time for me I thought if I train just once and save a weight for test since I'm interest by just one object.

**Comment by wenbowen123** [comment]
for the same object instance, once you use BundleSDF to create a textured model, you might want to use [se(3)-TrackNet](https://github.com/wenbowen123/iros20-6d-pose-tracking) for future inference.
