### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Jawae** [NVlabs/BundleSDF#57]
It happened a Segmentation fault (core dumped) when running the function frame.setNewInitCoordinate(). 
Can you help me ? TShanks

**Comment by wenbowen123** [comment]
can you make sure you are able to run on the demo data first?

**Comment by Jawae** [comment]
> can you make sure you are able to run on the demo data first?

I met the same issue when I run it on ho3d and milk dataset.

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/BundleTrack/src/Frame.cpp#L162
did you see the output ply file coming out of this?

**Comment by Jawae** [comment]
> https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/BundleTrack/src/Frame.cpp#L162
> 
> 
> did you see the output ply file coming out of this?

No. When I debug I find that the segment fault happend in the function setNewInitCoordinate()

**Comment by wenbowen123** [comment]
that's why I asked, because this line is in middle of setNewInitCoordinate()

**Comment by Jawae** [comment]
> 

There is no output ply file.

**Comment by Jawae** [comment]
> that's why I asked, because this line is in middle of setNewInitCoordinate()

There is cloud_init.ply file but no cloud_for_init_coord.ply file. Thanks

**Comment by wenbowen123** [comment]
what does the cloud_init.ply look like, can you share the file? And did you run this in docker container?

**Comment by Jawae** [comment]
> 

[cloud_init.zip](https://github.com/NVlabs/BundleSDF/files/12318517/cloud_init.zip)
The file is attached. 

I did not run this in a docker container. I build up the environment via conda

**Comment by Jawae** [comment]
> > 
> 
> [cloud_init.zip](https://github.com/NVlabs/BundleSDF/files/12318517/cloud_init.zip) The file is attached.
> 
> I did not run this in a docker container. I build up the environment via conda

But I installed the required package according to the dockerfile

**Comment by wenbowen123** [comment]
if you run inside docker, it will probably be fine.
