### ISSUE TITLE
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution

### ISSUE THREAD

**Issue by GokulSoman** [NVlabs/BundleSDF#58]
I am facing this error while trying to run the code. I am trying to run the code in the milk can dataset provided in the readme.
This is the command I used to run the code
```
python run_custom.py --mode run_video --video_dir milk_can/2022-11-18-15-10-24_milk/  --out_folder debug/milk_aug_7 --use_segmenter 1 --use_gui 0 --debug_level 0

```
I am attaching the error as well. The error occurs when the code goes through the same steps (tracker.run) for many time, and then crashes.

```
Traceback (most recent call last):
  File "run_custom.py", line 211, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 111, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/gokuls/BundleSDF/bundlesdf.py", line 546, in run
    self.process_new_frame(frame)
  File "/home/gokuls/BundleSDF/bundlesdf.py", line 437, in process_new_frame
    self.find_corres([(frame, ref_frame)])
  File "/home/gokuls/BundleSDF/bundlesdf.py", line 365, in find_corres
    corres = self.loftr.predict(rgbAs=imgs[::2], rgbBs=imgs[1::2])
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/gokuls/BundleSDF/loftr_wrapper.py", line 59, in predict
    self.matcher(tmp)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gokuls/BundleSDF/BundleTrack/LoFTR/src/loftr/loftr.py", line 49, in forward
    feats_c, feats_f = self.backbone(torch.cat([data['image0'], data['image1']], dim=0))
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gokuls/BundleSDF/BundleTrack/LoFTR/src/loftr/backbone/resnet_fpn.py", line 116, in forward
    x1_out = self.layer1_outconv2(x1_out+x2_out_2x)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
```

I found one reason for this issue could be memory overflow in GPU. So I reduced the batch size to 1 in loftr_wrapper.py
![image](https://github.com/NVlabs/BundleSDF/assets/19678980/25affb21-2774-4bc3-b4c0-f42edbc6c891)

The other reason was that the pytorch version and the cuda versions may not match.
But this also I verified as not an issue
![image](https://github.com/NVlabs/BundleSDF/assets/19678980/11549c4a-734d-44a8-96cb-179f9952f757)

I am using an NVIDIA GeForce RTX 3080 GPU. (10 GB)
after reducing the batch size, I tracked the memory usage at each step as well 

```
used memory before tracker run: 176.0 - 108.14453125 = 67.85546875/10009.4375
used memory before empty cache: 632.0 - 133.2919921875 = 498.7080078125/10009.4375
used memory after empty cache: 150.0 - 133.2919921875 = 16.7080078125/10009.4375
used memory before empty cache: 664.0 - 143.04052734375 = 520.95947265625/10009.4375
used memory after empty cache: 176.0 - 143.04052734375 = 32.95947265625/10009.4375
```

Kindly help, as I am unable to debug the exact reason for this issue.

**Comment by wenbowen123** [comment]
Hi, did you install nvidia docker (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)?

**Comment by GokulSoman** [comment]
Hi Bowen,
Yes, nvidia docker is installed. 
I am able to use cuda in docker. The **tracker.run** command runs for the provided milk can dataset for 238 iterations (238 images), after which the GPU becomes full.
(the previous memory usage I had measured was through code (torch functions) and wasn't accurate. Using nvidia-smi, I can see the memory getting filled up.

But something seems to fill up the memory that I am not able to debug (as part of the code is in CPP).
When I checked, the code crashed at the 238th iteration on running the self.process_new_frame function.
There seems to be something that gets added to the memory that is not being cleaned up even though I used a batch size of 1.

**Comment by wenbowen123** [comment]
it seems like it's because loftr is OOM. We will push a fix for this later. For now as work around, can you reduce the batch size?
https://github.com/NVlabs/BundleSDF/blob/master/loftr_wrapper.py#L43

**Comment by wenbowen123** [comment]
what is the memory of your GPU?

**Comment by GokulSoman** [comment]
> it seems like loftr is OOM. We will push a fix for this later. For now as work around, can you reduce the batch size?
> https://github.com/NVlabs/BundleSDF/blob/master/loftr_wrapper.py#L43

Yep, I tried this method as well. I reduced the batch size I tried till I reached a batch size of 1. But still crashes. I am using RTX 3080 with a memory of 10 gb.

**Comment by wenbowen123** [comment]
10GB is a bit small. As work around, you can reduce the image size (shorter_side) https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/run_custom.py#L70

This will affect the quality but should address your issue.

**Comment by GokulSoman** [comment]
> 10GB is a bit small. As work around, you can reduce the image size (shorter_side)
> 
> https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/run_custom.py#L70
> 
> This will affect the quality but should address your issue.
Hi Bowen,
I tried this method as well. This does help in getting a few more iterations, but ultimately it crashed when run on the milk can dataset (1932 images).I had reduced resolution to 480x360 (from 640x480).
Only workaround I have figured to complete the whole script is to use a subset of the dataset (max. 200-300 images),

**Comment by wenbowen123** [comment]
yes, the best would be use a GPU with larger memory.
