### ISSUE TITLE
Tracker pose estimation result seems to be wrong

### ISSUE THREAD

**Issue by bgyooPtr** [NVlabs/BundleSDF#59]
Since the library uses docker, there should be no problem. Is it a hardware problem?

Env: Ubuntu20.04 / RTX Titan 24GB

`python run_custom.py --mode run_video --video_dir 2022-11-18-15-10-24_milk --out_folder out_bundlesdf_2022-11-18-15-10-24_milk --use_segmenter 1 --use_gui 1 --debug_level 2`
[Video](https://nas.banggil.com/sharing/cHaWn91ii)

**Comment by wenbowen123** [comment]
The pose is not wrong, see [this](https://github.com/NVlabs/BundleSDF/issues/56).
It tracks the object pose, so it's good if the coordinate system is consistent along the video.
