### ISSUE TITLE
Due to license issues, we are not able to include XMem in this codebase for running segmentation online. If you are interested in doing so, please download the code separately and add a wrapper in segmentation_utils.py.

### ISSUE THREAD

**Issue by wang-shuaikang** [NVlabs/BundleSDF#60]
Hello, I am new to this project. The segmentation here should be merged into the segmentation_utils.py file with the code in Xmem. Can you explain this in detail? Please

**Comment by wenbowen123** [comment]
The Xmem is GPL license which we don't plan to include in our codebase or support its usage. So if you want to use that, you need to combine Xmem with BundleSDF yourself.

**Comment by htchr** [comment]
Hello,

The Xmem code linked in the README appears to be MIT license. Could you please add an example of how to use it?

Thank you,
