### ISSUE TITLE
Error while bash build.sh

### ISSUE THREAD

**Issue by wang-shuaikang** [NVlabs/BundleSDF#62]
cd docker
docker build --network host -t nvcr.io/nvidian/bundlesdf .
cd docker && bash run_container.sh
# Inside docker container, compile the packages which are machine dependent
bash build.sh
What is this used for? Is bash build.sh going to be in the docker file?

**Comment by wenbowen123** [comment]
Duplicate of https://github.com/NVlabs/BundleSDF/issues/63
