### ISSUE TITLE
Where are the mask and mask_vis in the example milk dataset generated from?

### ISSUE THREAD

**Issue by wang-shuaikang** [NVlabs/BundleSDF#64]
There are also annotate_poses, tf, ply, mask.png in milk, are these all necessary or optional?

**Comment by wenbowen123** [comment]
The only files needed are listed here https://github.com/NVlabs/BundleSDF#run-on-your-custom-data

**Comment by wenbowen123** [comment]
To get the mask, you can use SAM or Photoshop, or Mask-RCNN
