### ISSUE TITLE
problem with bash build.sh

### ISSUE THREAD

**Issue by Jekyll6104** [NVlabs/BundleSDF#65]
Execute to the last step, that is “make -j11 ” , what is the error reported like this

[ 80%] Building CXX object CMakeFiles/BundleTrack.dir/src/Bundler.cpp.o
[ 80%] Building CXX object CMakeFiles/BundleTrack.dir/src/Frame.cpp.o
In file included from /home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/FeatureManager.cpp:12:0:
/home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/FeatureManager.h:15:10: fatal error: zmq_addon.hpp: No such file or directory
 #include <zmq_addon.hpp>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/BundleTrack.dir/build.make:89: recipe for target 'CMakeFiles/BundleTrack.dir/src/FeatureManager.cpp.o' failed
make[2]: *** [CMakeFiles/BundleTrack.dir/src/FeatureManager.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/Frame.h:18:0,
                 from /home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/Frame.cpp:12:
/home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/FeatureManager.h:15:10: fatal error: zmq_addon.hpp: No such file or directory
 #include <zmq_addon.hpp>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/BundleTrack.dir/build.make:103: recipe for target 'CMakeFiles/BundleTrack.dir/src/Frame.cpp.o' failed
make[2]: *** [CMakeFiles/BundleTrack.dir/src/Frame.cpp.o] Error 1
In file included from /home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/Frame.h:18:0,
                 from /home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/Bundler.h:17,
                 from /home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/Bundler.cpp:15:
/home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/src/FeatureManager.h:15:10: fatal error: zmq_addon.hpp: No such file or directory
 #include <zmq_addon.hpp>
          ^~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/BundleTrack.dir/build.make:75: recipe for target 'CMakeFiles/BundleTrack.dir/src/Bundler.cpp.o' failed
make[2]: *** [CMakeFiles/BundleTrack.dir/src/Bundler.cpp.o] Error 1
CMakeFiles/Makefile2:112: recipe for target 'CMakeFiles/BundleTrack.dir/all' failed
make[1]: *** [CMakeFiles/BundleTrack.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

This error is still reported after successfully installing the package libzmq3-dev
I tried various methods and were unable to avoid this error
So I'd like to ask you if removing this last step from this file will affect the operation of the code

**Comment by wenbowen123** [comment]
Did you run this in a docker container?

**Comment by Jekyll6104** [comment]
Yes, I created the docker container and ran build.sh in it, and this error occurred


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/BundleSDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 凌晨1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/BundleSDF] problem with bash build.sh (Issue #65)





 
Did you run this in a docker container?

**Comment by Jekyll6104** [comment]
like this

(base) hc:~/hou/BundleSDF/BundleSDF-master/docker$ sudo bash run_container.sh  
bundlesdf
access control disabled, clients can connect from any host

==========
== CUDA ==
==========

CUDA Version 11.3.1

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION &amp; AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

and run cmake ..
(py38) root@hc:/home/huangcheng/hou/BundleSDF/BundleSDF-master/BundleTrack/build
# cmake ..
-- The CUDA compiler identification is NVIDIA 11.3.109
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_CXX_COMPILER_VERSION: 7.5.0
-- Found Boost: /usr/include (found version "1.65.1") found components: system program_options serialization 

Then an error occurred when executing the final step  make -j11

**Comment by wenbowen123** [comment]
if you remove all zmq related code, it might work. But it's still odd that you are getting this error with docker.

**Comment by Jekyll6104** [comment]
So you mean that after deleting the hpp files mentioned in the error, there is no problem running the code, right?


I'll try rebuilding docker on another computer, and if it still gets an error in the end, I'll take your solution, thank you very much for your answer.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/BundleSDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 上午9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/BundleSDF] problem with bash build.sh (Issue #65)





 
if you remove all zmq related code, it might work. But it's still odd that you are getting this error with docker.

**Comment by Jekyll6104** [comment]
I tried to remove all the code related to zmq, but it doesn't seem like I can build the my_cpp file successfully, it still doesn't seem to work, I'll keep trying to fix it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NVlabs/BundleSDF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 上午9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NVlabs/BundleSDF] problem with bash build.sh (Issue #65)





 
if you remove all zmq related code, it might work. But it's still odd that you are getting this error with docker.

**Comment by Jekyll6104** [comment]
> do you have this file `/usr/include/zmq_addon.hpp` inside docker?

I have searched, but did not find, may I ask is this automatically generated, or after the installation of the dependency package with it

**Comment by wenbowen123** [comment]
if you built docker successfully, you should have this file.

**Comment by Jekyll6104** [comment]
> if you built docker successfully, you should have this file.

After running it, the output looks like this
(base) huangcheng@hc:~/hou/BundleSDF/BundleSDF-master/docker$ sudo bash run_container.sh 
[sudo] huangcheng 的密码： 
bundlesdf
access control disabled, clients can connect from any host

==========
== CUDA ==
==========

CUDA Version 11.3.1

Container image Copyright (c) 2016-2022, NVIDIA CORPORATION &amp; AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

**Comment by wenbowen123** [comment]
what is this error?
![image](https://github.com/NVlabs/BundleSDF/assets/23078192/7701eb2f-50a0-4de6-a9fb-6cce70c9a162)

**Comment by Jekyll6104** [comment]
> what is this error? ![image](https://user-images.githubusercontent.com/23078192/261124843-7701eb2f-50a0-4de6-a9fb-6cce70c9a162.png)

What I understand is that maybe the cuda path pointed to when I modified the dockerfile was not correct. This may be related to finding the gpu. After I deleted the --gpus all in the run container.sh file, it ran successfully.
![Uploading Screenshot_2023-08-17-04-20-32-22_e39d2c7de19156b0683cd93e8735f348.jpg…]()

**Comment by Jekyll6104** [comment]
could you see the picture
![Uploading IMG_20230817_042625.jpg…]()

**Comment by Jekyll6104** [comment]
> what is this error? ![image](https://user-images.githubusercontent.com/23078192/261124843-7701eb2f-50a0-4de6-a9fb-6cce70c9a162.png)

and I changed the dockerfile as follows：

RUN cd / && git clone https://github.com/pybind/pybind11 &&\
    cd pybind11 && git checkout v2.10.0 &&\
    mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF &&\
    make -j6 && make install

WORKDIR /

COPY ./yaml-cpp /yaml-cpp

RUN cd yaml-cpp && git checkout yaml-cpp-0.7.0 &&\
    mkdir build && cd build && cmake .. -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DINSTALL_GTEST=OFF -DYAML_CPP_BUILD_TESTS=OFF -DYAML_BUILD_SHARED_LIBS=ON &&\
    make -j6 && make install

SHELL ["/bin/bash", "--login", "-c"]

RUN cd / && wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    /bin/bash /miniconda.sh -b -p /opt/conda &&\
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh &&\
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc &&\
    /bin/bash -c "source ~/.bashrc" && \
    /opt/conda/bin/conda update -n base -c defaults conda -y &&\
    /opt/conda/bin/conda config --set ssl_verify no && \
    /opt/conda/bin/conda config --add channels conda-forge &&\
    /opt/conda/bin/conda create -n py38 python=3.8


ENV PATH $PATH:/opt/conda/envs/py38/bin


RUN conda init bash &&\
    echo "conda activate py38" >> ~/.bashrc &&\
    # Use 'bash -l' to activate the conda environment
    /bin/bash -l -c "conda activate py38 && \
    pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 && \
    pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable' && \
    pip install trimesh opencv-python matplotlib imageio tqdm open3d ruamel.yaml sacred kornia pymongo pyrender jupyterlab ninja" &&\
    conda install -y -c anaconda scipy


WORKDIR /

COPY ./kaolin /kaolin


ENV CUDA_HOME /usr/local/cuda-11.3
ENV LD_LIBRARY_PATH /usr/local/cuda-11.3/lib64
ENV OPENCV_IO_ENABLE_OPENEXR=1


RUN imageio_download_bin freeimage

RUN conda activate py38 && cd /kaolin &&\
    # sed -i "223i    extra_compile_args['nvcc'] += ['-gencode=arch=compute_52,code=sm_52', '-gencode=arch=compute_60,code=sm_60', '-gencode=arch=compute_61,code=sm_61', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_80,code=sm_80', '-gencode=arch=compute_80,code=compute_80', '-Wno-deprecated-gpu-targets']" setup.py &&\
    FORCE_CUDA=1 python setup.py develop


#### Kaolin will change numpy version
RUN pip install -U transformations einops scikit-image awscli awscli-plugin-endpoint gputil xatlas pymeshlab rtree dearpygui pytinyrenderer PyQt5 cython-npm chardet openpyxl

RUN apt-get update --fix-missing && \
    apt-get install -y rsync lbzip2 pigz zip p7zip-full p7zip-rar]


Because the network connection is not very good, there are some dependency packages I downloaded to the local and then copied into the container, do you think there is something wrong with my dockerfile file? Will it not compile successfully because of some changes in it

**Comment by wenbowen123** [comment]
I'm not sure why you dont have the zmq. You might want to try copy that as well. The best is to not use copy at all, and only use docker build.

**Comment by Jekyll6104** [comment]
> I'm not sure why you dont have the zmq. You might want to try copy that as well. The best is to not use copy at all, and only use docker build.

Thank you very much. I will try to rebuild docker build. In addition, I would like to ask if you only need to modify the top ubuntu version of the dockerfile file in ubuntu18.04, and do other modifications need to be made

**Comment by wenbowen123** [comment]
the Ubuntu version doesn't need to change. It is unrelated to your own system's Ubuntu version

**Comment by Jekyll6104** [comment]
> the Ubuntu version doesn't need to change. It is unrelated to your own system's Ubuntu version

Thank you very much for your response. Finally, I have another question. I am in China, so sometimes it will be very difficult or fail to download things from github. I would like to ask whether the path of the dependent package can be changed to the corresponding domestic mirror source.

**Comment by wenbowen123** [comment]
I never tried this, but it might worth trying.
