### ISSUE TITLE
File "/home/huangcheng/hou/BundleSDF/BundleSDF-master/bundlesdf.py", line 15, in &lt;module&gt;     import my_cpp ModuleNotFoundError: No module named 'my_cpp'

### ISSUE THREAD

**Issue by wang-shuaikang** [NVlabs/BundleSDF#66]
Full error:
(py38) root@hc:/home/huangcheng/hou/BundleSDF/BundleSDF-master# python run_ho3d.py --video_dirs /home/huangcheng/hou/BundleSDF/BundleSDF-master/HO3D_v3/evaluation/MPM10 --out_dir /home/huangcheng/hou/BundleSDF/BundleSDF-master/ho3d_our
Traceback (most recent call last):
  File "run_ho3d.py", line 10, in &lt;module&gt;
    from bundlesdf import *
  File "/home/huangcheng/hou/BundleSDF/BundleSDF-master/bundlesdf.py", line 15, in &lt;module&gt;
    import my_cpp
ModuleNotFoundError: No module named 'my_cpp'

**Comment by wenbowen123** [comment]
you need to run bash build.sh in the docker container.
