### ISSUE TITLE
May I ask whether this video sequence is input after recording with the depth camera, or it can be given during the recording?In the same way, the pose estimation can be estimated during the recording, or it can only be estimated after a period of recording. If there are only two frames of pictures, can the poses of these two frames be estimated?

### ISSUE THREAD

**Issue by wang-shuaikang** [NVlabs/BundleSDF#72]

**Comment by wenbowen123** [comment]
You can run BundleSDF in online mode. But you would need to write an online segmentation. You can use XMem to do this. Then you can feed the RGBD (from live camera), mask to BundleSDF.  

For the 2 frames, is the pose difference very big? If they are neighboring frames (from a video) with small pose difference, BundleSDF can be applied out-of-box.

**Comment by wang-shuaikang** [comment]
> 您可以在在线模式下运行 BundleSDF。但你需要编写一个在线分段。您可以使用 XMem 来执行此操作。然后，您可以将 RGBD（来自实时摄像机）、掩模提供给 BundleSDF。
> 
> 2帧，姿势差别很大吗？如果它们是姿势差异较小的相邻帧（来自视频），则可以开箱即用地应用 BundleSDF。

Dear author, your project team connected the camera for real-time operation at that time, or processed the shooting results after collecting with the camera. are both acceptable？

**Comment by wenbowen123** [comment]
both are doable. As I mentioned here, for online purpose, you'd need to write an online segmenter.
