### ISSUE TITLE
python run_ho3d.py face error

### ISSUE THREAD

**Issue by gyhandy** [NVlabs/BundleSDF#75]
When I run python run_ho3d.py in the docker container, it has the error: ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/conda/envs/py38/lib/python3.8/site-packages/scipy/spatial/_ckdtree.cpython-38-x86_64-linux-gnu.so)

**Comment by wenbowen123** [comment]
does this work for you https://github.com/NVlabs/BundleSDF/issues/2 ?

**Comment by gyhandy** [comment]
Problem solved, thanks!
