### ISSUE TITLE
Face error when Run global refinement post-processing to refine the mesh

### ISSUE THREAD

**Issue by gyhandy** [NVlabs/BundleSDF#79]
When I run the milk demo, 
2) (Optinal) Run global refinement post-processing to refine the mesh
python run_custom.py --mode global_refine 

Face the error:
cp: cannot stat 'BundleSDF/data/output_milk//nerf_with_bundletrack_online/image_step_*.png': No such file or directory

Could you please help to check? Why it need to add '/' in save_dir?

**Comment by wenbowen123** [comment]
https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/run_custom.py#L107C19-L107C20
this line should have already run the global refinement. So you dont need to run that line. There should be a mesh file in your output dir. I'll push an update to the readme.

**Comment by gyhandy** [comment]
Hi, thanks for your reply! Even in the first step, we face the same error

# 1) Run joint tracking and reconstruction
python run_custom.py --mode run_video --video_dir OUR/FOLDER --out_folder OUR/FOLDER --use_segmenter 1 --use_gui 0--debug_level 2

Face the error:
cp: cannot stat 'BundleSDF/data/output_milk//nerf_with_bundletrack_online/image_step_*.png': No such file or directory

Could you please help to check? Thanks!

**Comment by wenbowen123** [comment]
@gyhandy if there is only that error, it  shouldn't interfere anything. Did you see any other errors thrown? Since the final outputs are the poses (in `cam_in_ob` folder), and the reconstruction `textured_mesh.obj`, if you have those, the run is good.
