### ISSUE TITLE
the pose of 3d model does not match the original 2D picture

### ISSUE THREAD

**Issue by swearos** [NVlabs/BundleSDF#81]
1. The pose of the generated 3D object does not match the original image, and there is a very large deviation
2. The box generated by the 3D model cannot fit the object in the 2D image
https://github.com/wenbowen123/BundleTrack/issues/48

**Comment by wenbowen123** [comment]
The saved poses are the tracked motions for the object (how much does the object rotate/translation throughout the video). If you directly plot using them, you can still get a box as if it's attached to the object, while the object moves. However, like you observed it's not necessarily axis-aligned. Back then, we made the axis-aligned box only for visualization purpose. To do so, you can either manually rotate the mesh to make it axis-aligned or compute an oriented box that fits it.  

Please note that for an object, there are infinite ways to define its coordinate system. Even for the axis-aligned box, it's not unique. E.g. you can make Z axis up, or X or Y axis up, etc.

**Comment by swearos** [comment]
Thank you very much for your thoughtful reply.
My question is, **how to get the right pose of the 3D object corresponding to the original 2D image?**

I run milk dataset, textured_mesh.obj works really well.
But the rendered object pose is very different from the corresponding 2D original image. 
I try to save the ply file corresponding to each frame in saveNewframeResult, but the same problem still exists.

Left: org_2D_pic, Right: Mesh_real_world.obj, generated corresponding to the picture
![image](https://github.com/NVlabs/BundleSDF/assets/10892059/ef6d2be1-3588-4707-8bb8-a58fee5d6623)
I try to manually rotate this 3D model, maybe the mesh corresponding to this picture should be as follows
![image](https://github.com/NVlabs/BundleSDF/assets/10892059/029c2647-8f85-4e57-94b5-8081d980f331)

**Comment by swearos** [comment]
1. If I want to get the accurate 3D pose information of the object in the video stream, do I have to know the pose of the initial object, such as the external parameter information of the camera, to get the pose information of the first frame of the object in the world coordinate system?
2. If the pose information of the object in the first frame is necessary, can you share how to obtain the pose information of the milk dataset?

**Comment by wenbowen123** [comment]
If you apply the first pose from the `ob_in_cam` folder to the reconstructed mesh and project (render) to the 2D image, you should be able to match to the original image. Not sure how you exactly implemented this. Maybe I can tell what goes wrong if you share your code snippet.

If your goal is just to achieve this, no external pose information is needed.

**Comment by swearos** [comment]
The code for drawing 3D BOX comes from [link1](https://github.com/wenbowen123/BundleTrack/issues/48#issuecomment-1143964930) , 
draw_bbox(K, img, ob_in_cam, bbox, color_id, linewidth=2), 
the input parameter ob_in_cam comes from the ob_in_cam folder, 
bbox comes from the points in the corresponding nerf/mesh_real_world.obj, points*=1000.

The generated 3D box and the 3D object are very inconsistent, and the difference from the gif is large. 

https://github.com/NVlabs/BundleSDF/assets/10892059/78b242be-da3b-418a-a049-e965f3c286b4

I suspect that the reason is that the pose of the mesh is quite different from the original image [link2](https://github.com/NVlabs/BundleSDF/issues/81#issuecomment-1687423449), resulting in an abnormality in the generated 3D box.

**Comment by wenbowen123** [comment]
instead of plotting the bbox, can you project the mesh to check?

The box definition could be different. The demo I showed is just one possible way to define the box, like I mentioned [here](https://github.com/NVlabs/BundleSDF/issues/81#issuecomment-1687364678).

**Comment by lfz-5** [comment]
> instead of plotting the bbox, can you project the mesh to check?
> 
> The box definition could be different. The demo I showed is just one possible way to define the box, like I mentioned [here](https://github.com/NVlabs/BundleSDF/issues/81#issuecomment-1687364678).
Hi, I am new to 3D vision and CG, would you mind to tell me more about how to project the mesh to check or what key word 
 I should search. Thanks a lot.

**Comment by wenbowen123** [comment]
@lfz-5 @swearos 
see our recent update https://github.com/NVlabs/BundleSDF/issues/90
