### ISSUE TITLE
Depth format

### ISSUE THREAD

**Issue by ZisongXu** [NVlabs/BundleSDF#82]
Hi Dear:

Thanks for the nice work. 

When I tried this code on my own examples, I met the problem (I did not see errors):

![Screenshot from 2023-08-23 15-28-42](https://github.com/NVlabs/BundleSDF/assets/36726128/9622bd99-2506-4f67-9639-a515bae1eba4)

```
[loftr_wrapper.py] image0: torch.Size([1, 1, 400, 400])
[loftr_wrapper.py] net forward
[loftr_wrapper.py] mconf, 0.2009592056274414 0.9755884408950806
[loftr_wrapper.py] pair_ids (345,)
[loftr_wrapper.py] corres: (345, 5)
[2023-08-23 07:24:21.569] [warning] [FeatureManager.cpp:1589] start multi pair ransac GPU, pairs#=1
[2023-08-23 07:24:21.569] [warning] [FeatureManager.cpp:1695] after ransac, frame 01000 and 0100 has too few matches #0, ignore
> /home/sc19zx/docker/BundleSDF/bundlesdf.py(452)process_new_frame()
-> for id in ids:
(Pdb)
```
It wants me to input something? I do not know. Do you have any ideas about that?

Thanks a lot!!!

**Comment by ZisongXu** [comment]
And then when I press Ctrl D, it generates some thing like that:


```
(Pdb) --KeyboardInterrupt--
(Pdb) --KeyboardInterrupt--
(Pdb) 
Traceback (most recent call last):
  File "run_custom.py", line 204, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 103, in run_one_video
    tracker.run(color, depth, K, id_str, mask=mask, occ_mask=None, pose_in_model=pose_in_model)
  File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 551, in run
    logging.info(f"processNewFrame done {frame._id_str}")
  File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 452, in process_new_frame
    for id in ids:
  File "/home/sc19zx/docker/BundleSDF/bundlesdf.py", line 452, in process_new_frame
    for id in ids:
  File "/opt/conda/envs/py38/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/opt/conda/envs/py38/lib/python3.8/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
[2023-08-23 07:38:20.186] [warning] [Bundler.cpp:59] Destructor
(py38) root@server:/home/sc19zx/docker/BundleSDF# 

```

**Comment by wenbowen123** [comment]
are you able to share how your video looks like? It seems like not matches can be found between the frames.

**Comment by ZisongXu** [comment]
Here's the link to my video. The images are stored in the rosbag.
[bundleSDF_video](https://drive.google.com/drive/folders/1JZNDidJUdU7XPMDahGnn6wK3vC4mnyNF?usp=sharing)

**Comment by wenbowen123** [comment]
You depth seems in the wrong format. It has to be uint16 and unit is mm.

**Comment by wenbowen123** [comment]
once you run bundleSDF, there is a ply file saved in the output dir (something called "cloudXXX"). You can viz that. It looks very skewed given your data, so your depth is probably wrong.

PIL is not recommended. You can save the depth with opencv
`cv2.imwrite('depth.png', (depth_meter*1000).astype(np.uint16))`

**Comment by ZisongXu** [comment]
Thank you very much! I am looking into it! I will update as I get some results.

**Comment by ZisongXu** [comment]
I am very sorry for my late reply, I have been trying to change the value of the depth image. I have used the code you gave above to reacquire the depth image. I found that I was giving the wrong values to my cam_K.txt, and I found that the naming order of the images produced an error. When I reran the algorithm after fixing it, it produced a new error:

**Comment by ZisongXu** [comment]
By the way, all the ply files I got after all the training was weird:
![Screenshot from 2023-09-12 10-28-54](https://github.com/NVlabs/BundleSDF/assets/36726128/258dd952-8b4b-44eb-bd57-cf7906ec7082)

![Screenshot from 2023-09-12 10-28-58](https://github.com/NVlabs/BundleSDF/assets/36726128/45d328a1-c4fe-405a-b7dc-3e4b46135067)

![Screenshot from 2023-09-12 10-31-55](https://github.com/NVlabs/BundleSDF/assets/36726128/e824fbf7-2e3e-4387-bfc6-905f462879fa)

**Comment by ZisongXu** [comment]
Hi Dear wenbo:

We did some other tests, we even switched to a new camera (from D435i camera to D455 camera) to collect new dataset, but we still had the problem described above. I think maybe my depth image is still incorrect. Could I ask how you get your depth image dataset?

Does the quality of the mask images affect the results? Because I've noticed that the mask images I get using XMem are not completed accurate for a new frames.

**Comment by wenbowen123** [comment]
The depth is wrong. I'd still suggest resolving that before trying other things. You can compare with our example data to get a sense about the difference. Curious, what tool did you use to capture the real sense data? If you are familiar with ROS, you can use https://github.com/IntelRealSense/realsense-ros

BundleSDF is robust to moderate noisy segmentation masks. So not completely accurate should be fine.

**Comment by ZisongXu** [comment]
Can I ask another question: Does this project requires the specific resolution(640*480) images? Our normal image is 1280*720, but we have scaled it to 640*480

**Comment by wenbowen123** [comment]
there is no need to for that. Even if you want to scale, BundleSDF has a config to set the desired shorter side https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/run_custom.py#L70
Setting by yourself could be error prone.

**Comment by wenbowen123** [comment]
this looks right. Sure, feel free to write the summary. Thanks for sharing

**Comment by ZisongXu** [comment]
Thank you so much for helping me, here's a summary in case subsequent workers encounter similar problems:

After configuring the author's code successfully, we try our own example. But it seems that something is wrong with the depth image. The camera we are using is a D435i, and using [https://github.com/IntelRealSense/realsense-ros](https://github.com/IntelRealSense/realsense-ros) to collect rgb and depth images.

**Comment by monajalal** [comment]
@ZisongXu [bundleSDF_video](https://drive.google.com/drive/folders/1JZNDidJUdU7XPMDahGnn6wK3vC4mnyNF?usp=sharing) 

^^ is not accessible anymore. Would you please be able to share a rosbag for a working capture as an example? This would be very helpful. Thanks a lot.

**Comment by ZisongXu** [comment]
> @ZisongXu [bundleSDF_video](https://drive.google.com/drive/folders/1JZNDidJUdU7XPMDahGnn6wK3vC4mnyNF?usp=sharing)
> 
> ^^ is not accessible anymore. Would you please be able to share a rosbag for a working capture as an example? This would be very helpful. Thanks a lot.

https://leeds365-my.sharepoint.com/:u:/g/personal/sc19zx_leeds_ac_uk/Eb3AX-sOgWtNrgk-jG2nhqABlJRj28qyNQHKkIyWVYYPwg?e=TMzeQN
can you try this?

**Comment by monajalal** [comment]
@ZisongXu  could you please tell how you converted this rosbag into a depth and rgb video?
I get error with `/usr/bin/python3.10 ros2bag2video.py ~/Downloads/cheezit_1280_whole.bag` in ros 2 humble in Ubuntu 22.04. Thanks a lot.

**Comment by ZisongXu** [comment]
> @ZisongXu could you please tell how you converted this rosbag into a depth and rgb video? I get error with `/usr/bin/python3.10 ros2bag2video.py ~/Downloads/cheezit_1280_whole.bag` in ros 2 humble in Ubuntu 22.04. Thanks a lot.
> 
> I was trying to inspect the topics in your ros bag but got this error:
> 
> ```
> (base) mona@ada:~/rosbag2video$ ros2 bag info  /home/mona/Downloads/cheezit_1280_whole.bag
> 
> closing.
> 
> closing.
> [ERROR] [1698864601.552300192] [rosbag2_storage]: No storage id specified, and no plugin found that could open URI
> No plugin detected that could open file /home/mona/Downloads/cheezit_1280_whole.bag
> (base) mona@ada:~/rosbag2video$ ls /home/mona/Downloads/cheezit_1280_whole.bag
> -rw-rw-r-- 1 mona mona 11G Nov  1 09:33 /home/mona/Downloads/cheezit_1280_whole.bag
> ```
> 
> also:
> 
> ```
> (base) mona@ada:~/Downloads$ md5sum cheezit_1280_whole.bag 
> 0a5d76c135327ebf702a358b2aec4398  cheezit_1280_whole.bag
> ```

`import os
import sys
import yaml
from rosbag.bag import Bag
import cv2

import roslib;   #roslib.load_manifest(PKG)
import rosbag
import rospy
import cv2
import numpy as np
import argparse
import os

from sensor_msgs.msg import Image
from cv_bridge import CvBridge
from cv_bridge import CvBridgeError

class ImageCreator():
    def __init__(self, bagfile, rgbpath, depthpath, rgbstamp, depthstamp):
        self.bridge = CvBridge()
        with rosbag.Bag(bagfile, 'r') as bag:
            for topic,msg,t in bag.read_messages():
                print(topic)
                if topic == "/camera/color/image_raw": #图像的topic；
                    # try:
                    cv_image = self.bridge.imgmsg_to_cv2(msg,"bgr8")
                    # except CvBridgeError as e:
                    #     print(e)
                    timestr = "%.6f" %  msg.header.stamp.to_sec()
                    #%.6f表示小数点后带有6位，可根据精确度需要修改；
                    image_name = timestr+ ".png" #图像命名：时间戳.png
                    # cv2.imshow("color", cv_image)
                    cv2.waitKey(1);
                    cv2.imwrite(rgbpath + image_name, cv_image)  #保存；

                    # #写入时间戳
                    # with open(rgbstamp, 'a') as rgb_time_file:
                    #     rgb_time_file.write(timestr+" rgb/"+image_name+"\n")
                elif topic == "/camera/aligned_depth_to_color/image_raw": #图像的topic；
                    # try:
                    cv_image = self.bridge.imgmsg_to_cv2(msg,"16UC1")
                    # except CvBridgeError as e:
                    #     print(e)
                    timestr = "%.6f" %  msg.header.stamp.to_sec()
                    #%.6f表示小数点后带有6位，可根据精确度需要修改；
                    image_name = timestr+ ".png" #图像命名：时间戳.png
                    
                    # cv2.imwrite(depthpath + image_name, cv_image)  #保存；
                    cv2.imwrite(depthpath + image_name, (cv_image).astype(np.uint16))

                    # #写入时间戳
                    # with open(depthstamp, 'a') as depth_time_file:
                    #     depth_time_file.write(timestr+" depth/"+image_name+"\n")

if __name__ == '__main__':
    ImageCreator('cheezit_new_2.bag', "/home/sc19zx/rgb/", "/home/sc19zx/depth/", 1, 1)`

**Comment by monajalal** [comment]
@ZisongXu 
Thank you so much for sharing your script.
I used it for your own cheezit dataset and run BundleSDF over it.

However, after quite some time, I got this error. Did you also get this error. I did set the zfar in run_custom.py to 1. What did you set it to?

Any chance you could please help me with this error?

```
(py38) root@ada:/home/mona/BundleSDF# python run_custom.py --mode run_video --video_dir /home/mona/BundleSDF/cheezit/ --out_folder /home/mona/BundleSDF/cheezit/out --use_segmenter 1 --use_gui 1 --debug_level 2

I am able to see visualizations before this error happens. Also, the fingertips, cause the mesh to be changed by a lot. Is it not robust to the hand handling the item?



[tool.py] compute_translation_scales done
translation_cvcam=[-0.00903649  0.00085566 -0.00491736], sc_factor=3.097254838324201
[nerf_runner.py] Octree voxel dilate_radius:1
level 0, resolution: 16
level 1, resolution: 20
level 2, resolution: 24
level 3, resolution: 28
level 4, resolution: 34
level 5, resolution: 41
level 6, resolution: 49
level 7, resolution: 59
level 8, resolution: 71
level 9, resolution: 85
level 10, resolution: 102
level 11, resolution: 123
level 12, resolution: 148
level 13, resolution: 177
level 14, resolution: 213
level 15, resolution: 256
GridEncoder: input_dim=3 n_levels=16 level_dim=2 resolution=16 -> 256 per_level_scale=1.2030 params=(20411696, 2) gridtype=hash align_corners=False
sc_factor 3.097254838324201
translation [-0.00903649  0.00085566 -0.00491736]
[nerf_runner.py] denoise cloud
[nerf_runner.py] Denoising rays based on octree cloud
[nerf_runner.py] bad_mask#=2942661
rays torch.Size([11686757, 12])
Start training
[nerf_runner.py] train progress 0/2001
[nerf_runner.py] Iter: 0, valid_samples: 637135/655360, valid_rays: 2025/2048, loss: 18.3850975, rgb_loss: 17.8837414, rgb0_loss: 0.0000000, fs_rgb_loss: 0.0000000, depth_loss: 0.0000000, depth_loss0: 0.0000000, fs_loss: 0.0453376, point_cloud_loss: 0.0000000, point_cloud_normal_loss: 0.0000000, sdf_loss: 0.3461785, eikonal_loss: 0.0000000, variation_loss: 0.0000000, truncation(meter): 0.0100000, pose_reg: 0.0000000, reg_features: 0.1098412, 

[nerf_runner.py] train progress 200/2001
[nerf_runner.py] train progress 400/2001
[nerf_runner.py] train progress 600/2001
[nerf_runner.py] train progress 800/2001
[nerf_runner.py] train progress 1000/2001
[nerf_runner.py] train progress 1200/2001
[nerf_runner.py] train progress 1400/2001
[nerf_runner.py] train progress 1600/2001
[nerf_runner.py] train progress 1800/2001
[nerf_runner.py] train progress 2000/2001
cp: cannot stat '/home/mona/BundleSDF/cheezit/out//nerf_with_bundletrack_online/image_step_*.png': No such file or directory
[nerf_runner.py] query_pts:torch.Size([33698267, 3]), valid:10917064
[nerf_runner.py] Running Marching Cubes
[nerf_runner.py] done V:(282910, 3), F:(562680, 3)
[acceleratesupport.py] OpenGL_accelerate module loaded
[arraydatatype.py] Using accelerated ArrayDatatype
project train_images 0/254
/home/mona/BundleSDF/nerf_runner.py:1530: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  uvs_unique = torch.stack((uvs_flat_unique%(W-1), uvs_flat_unique//(W-1)), dim=-1).reshape(-1,2)
project train_images 1/254
project train_images 2/254
project train_images 3/254
Traceback (most recent call last):
  File "run_custom.py", line 223, in <module>
    run_one_video(video_dir=args.video_dir, out_folder=args.out_folder, use_segmenter=args.use_segmenter, use_gui=args.use_gui)
  File "run_custom.py", line 107, in run_one_video
    run_one_video_global_nerf(out_folder=out_folder)
  File "run_custom.py", line 152, in run_one_video_global_nerf
    tracker.run_global_nerf(reader=reader, get_texture=True, tex_res=512)
  File "/home/mona/BundleSDF/bundlesdf.py", line 790, in run_global_nerf
    mesh = nerf.mesh_texture_from_train_images(mesh, rgbs_raw=rgbs_raw, train_texture=False, tex_res=tex_res)
  File "/home/mona/BundleSDF/nerf_runner.py", line 1511, in mesh_texture_from_train_images
    locations, distance, index_tri = trimesh.proximity.closest_point(mesh, pts)
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/trimesh/proximity.py", line 153, in closest_point
    all_candidates = np.concatenate(candidates)
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
Process Process-5:
Traceback (most recent call last):
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mona/BundleSDF/bundlesdf.py", line 89, in run_nerf
    join = p_dict['join']
  File "<string>", line 2, in __getitem__
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/py38/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-11-10 13:24:46.841] [warning] [Bundler.cpp:59] Destructor
[2023-11-10 13:24:46.843] [warning] [Bundler.cpp:59] Destructor
```

![Screenshot from 2023-11-10 16-27-47](https://github.com/NVlabs/BundleSDF/assets/1892917/60f74a9e-11d4-4072-8a6d-fc453b219177)
![Screenshot from 2023-11-10 16-30-32](https://github.com/NVlabs/BundleSDF/assets/1892917/ec8b97c4-937d-4965-8358-75ab2a16a509)
