### ISSUE TITLE
Using the reconstructed model for pose estimation

### ISSUE THREAD

**Issue by fuzhao123232** [NVlabs/BundleSDF#84]
请问作者我可以先把一个物体绕着相机拍一圈，然后建模，之后推理的时候直接用这个模型去做该物体的位姿估计吗？可以达到实时的效果吗

**Comment by monajalal** [comment]
@wenbowen123 do you have instructions on how to feed the data from milk output to iros20-6d-pose-trackig or any other custom object? Do you only need the CAD model or also the annotations? Any guidance would be really helpful.

**Comment by VenkatSBitra** [comment]
@wenbowen123 Could you please advice on the steps I should follow to get the model transferred to [iros20-6d-pose-tracking]?

**Comment by monajalal** [comment]
@wenbowen123 Thanks for your updates. There is no code published yet in your linked repo. We also had to let go of BundleSDF in our exploration since it is not fast for 6D pose estimation unfortunately.

How fast is Foundation Pose?

**Comment by VenkatSBitra** [comment]
@monajalal Can you suggest some alternatives that you have explored for fast 6D pose estimation?
