### ISSUE TITLE
docker is not successfully

### ISSUE THREAD

**Issue by 8baby8** [NVlabs/BundleSDF#85]
![image](https://github.com/NVlabs/BundleSDF/assets/101492509/16bfe450-e502-47a2-a37e-8647d91159d0)

**Comment by wenbowen123** [comment]
are you able to visit the website locally? https://github.com/PointCloudLibrary/pcl

**Comment by 8baby8** [comment]
> are you able to visit the website locally? https://github.com/PointCloudLibrary/pcl
Thank you. The above problem has been resolved,but new problems have emerged again.
![image](https://github.com/NVlabs/BundleSDF/assets/101492509/d106b976-38af-42c3-96bd-cddfece27635)

**Comment by wenbowen123** [comment]
In the file, you can replace `nvcr.io/nvidian/bundlesdf:latest` to `bundlesdf`
https://github.com/NVlabs/BundleSDF/blob/master/docker/run_container.sh
