### ISSUE TITLE
Not finding my_cpp

### ISSUE THREAD

**Issue by anil007-scorp** [NVlabs/BundleSDF#86]
Traceback (most recent call last):
  File "/home/anil/Projects/BundleSDF-master/run_custom.py", line 10, in <module>
    from bundlesdf import *
  File "/home/anil/Projects/BundleSDF-master/bundlesdf.py", line 15, in <module>
    import my_cpp
ModuleNotFoundError: No module named 'my_cpp'

I was trying to run bundleSDF on my system in ubuntu 22.04 I installed all the necessary modules and packages bu getting error

**Comment by swearos** [comment]
You need to compile the local lib library, check Readme

# Inside docker container, compile the packages which are machine dependent
bash build.sh

**Comment by anil007-scorp** [comment]
I am running it on ubuntu 22.04 I have downloaded all the pretrained files but I am stuck at docker setup. Can you please specify how should I run it on my system effectively

**Comment by wenbowen123** [comment]
have you tried using the docker? Which step did you get stuck on docker setup?

**Comment by ANIL-1528** [comment]
I can't able to compile the container using docker it keeps getting failed. 
can you please tell me how to setup docker and how to run BundleSDF step by step. I have downloaded all the pretrained and milk example files and structured those as mentioned on git but still not able to run

**Comment by wenbowen123** [comment]
can you elaborate "it keeps getting failed."?
