### ISSUE TITLE
approximate time for run_custom.py for milk and size of out_dir

### ISSUE THREAD

**Issue by monajalal** [NVlabs/BundleSDF#9]
could you please share how long the full execution of the following command takes for the milk zip you shared as for custom data?

`python run_custom.py --mode run_video --video_dir /milk/2022-11-18-15-10-24_milk/ --out_folder  /home/mona/BundleSDF/out_dir/ --use_segmenter 1 --use_gui 0 --debug_level 2`

also, what's the space of `out_dir` for you for milk custom data once the command is finished executing?
```
(base) mona@ard-gpu-01:~/BundleSDF$ du -h out_dir/
1.8G	out_dir/

```
^^ however run is not finished yet. I see a lot of intermediary folders created and this seems like a huge space requirement.

I am using a RTX 3080 laptop GPU and 64G ram and 16 CPU cores.

**Comment by wenbowen123** [comment]
you can decrease verbose logging by `--debug_level 0(or 1)`. Also you can adjust the sync mode [here](https://github.com/NVlabs/BundleSDF/blob/68ed8754808b0fa0e34dae2046199f134dfbc469/config.yml#L102). Currently it's strict sync. Depending on your hardware, async will get different kinds of results and is less stable. In general, we recommend a higher end machine.
