### ISSUE TITLE
Coordinate centre of the target object

### ISSUE THREAD

**Issue by ZisongXu** [NVlabs/BundleSDF#90]
Hi Dear Bowen:

Can I ask a question about the coordinate centre of the target object? 

When I got the pose of the target object for each frame in the “ob_in_cam” folder after running my own example. I could probably guess that the poses were in a coordinate system with the camera as the coordinate origin. But I'm not quite sure which point on the target object these coordinate values represent. Is it the centre of the target object?

In your project you mentioned rebuilding the model of the target object, will this new model be exported directly to the output folder?

Thanks a lot!

Best Regards
Zisong Xu

**Comment by wenbowen123** [comment]
The pose's translation term in the first frame is computed by taking the center of the visible point cloud. After the whole video processing, you can freely re-define the coordinate frame, such as taking the center and oriented box of the complete mesh.

You can refer to below about how we transform the tracked poses wrt the GT model
https://github.com/NVlabs/BundleSDF/blob/878cee2f1cda23810ff861f6fef2922c96c7a67e/benchmark_ho3d.py#L62

**Comment by ZisongXu** [comment]
Thanks a lot! 

1. Then may I ask if the position of the target object's coordinate system is unchanged for the rest of the time after the first frame has been determined?
2. After the position of the target object's coordinate system is determined, how did the project determin the ORIENTATION of the coordinate system? Also based on the point cloud distribution of the first frame?

Best Regards
Zisong XU

**Comment by ZisongXu** [comment]
Thanks a lot!!!

**Comment by ZisongXu** [comment]
Can I ask if there is a possibility to use the full ply file of the target object (Cheezit) given by ourselves in the first frame of the video? So that no matter what angle (first frame) of the Cheezit video I input in the future, as long as our target object is a Cheezit, the coordinate position of the target object will not change.

**Comment by wenbowen123** [comment]
You can refer to this for drawing 3D box https://github.com/NVlabs/BundleSDF/issues/91 

This might answer your question if you want to get pose tracking results for 3D box.

**Comment by ZisongXu** [comment]
Thank you so much for your reply. It would be great to be able to draw a 3D box around the target object! 

非常抱歉，可能是我的英语不太好，没有把问题描述清楚。

就是我的第一个问题是：如果我没有理解错您在上面回复我的问题的意思的话，在您的项目中，当我给出输入的数据之后，您的项目会根据第一帧的图片（depth，rgb，mask）来获取目标物体（Cheezit）的点云，根据点云的平均值获取目标物体（Cheezit）的坐标系中心。获取了目标物体（Cheezit）的坐标系中心之后，从第二帧开始，目标物体的坐标中心$T_{object}$将不会改变位置，所有的目标物体姿势的估计都基于这个固定点（$T_{object}$）在照相机坐标中心的位置（$^{camera}T_{object}$）。如果当我重新运行您的项目，输入新的数据集时（估计同一个目标物体Cheezit）但是第一帧目标物体（Cheezit）的位置角度不一样（第一帧的点云不一样），点云平均值不一样，所以目标物体（Cheezit）的坐标系中心也会改变，请问是这样吗？我不太清楚这个点云是以什么样的方式储存，请问是以ply文件的方式储存吗？如果以ply文件的方式储存，那请问有没有一种可能性，在我最开始输入数据的同时我给出已经有完整cheezit模型的ply文件作为第一帧的点云的输入来计算目标物体（cheezit）的坐标系中心，因为输入的ply文件是固定的，所以点云是固定的，所以点云的平均值是固定的，所以目标物体的坐标系中心是固定的。这样我就可以确保每一次如果想要跟踪同一个目标物体的姿势，目标物体的坐标系中心都是固定的？

第二个问题就是，在您的论文和项目网站中有提到可以帮助rebuild新的物体的模型（ply文件），请问我应该如何做？我们有两个想法，第一个想法是：在输入的新数据集视频（一帧一帧图片的形式）中，缓慢展示新的目标物体（special_bottle）的所有面儿（前后左右上下），这样您的项目能观测到新的目标物体（special_bottle）所有面儿，然后rebuild新的目标物体（special_bottle）的模型，然后储存在ply文件中，得到一个新的目标物体（special_bottle）的模型；第二个想法是：在输入的新的数据集视频中，新的目标物体（special_bottle）是固定的（只对照相机展示一个面儿），您的算法运行成功之后，我们会得到一个不完整的新的目标物体（special_bottle）的模型ply文件special_bottle_1.ply（因为我们在输入的视频中只展示了一个面儿）。接下来我稍微改变一下新的目标物体（special_bottle）在照相机中的角度，这样照相机能够看到新的目标物体（special_bottle）的新的面儿，然后再作为输入视频输入到您的代码中，并且我同时把special_bottle_1.ply作为新的输入，这样您的代码就能在special_bottle_1.ply的基础上得到一个新的不完整的模型（比第一次得到的ply文件完整一些但是不是完整的，因为我没有展示新的目标物体（special_bottle）所有的面儿）：special_bottle_2.ply。像这样逐步的移动新的目标物体（special_bottle），最后让照相机看到新的目标物体（special_bottle）所有的面儿之后，完整的模型也就创建成功了。

Best Regards
Zisong Xu

**Comment by wenbowen123** [comment]
1)In general, BundleSDF is applied to novel unseen object. So you can first run BundleSDF for that object the first time. From then on, you can see methods such as [se(3)-TrackNet](https://github.com/wenbowen123/iros20-6d-pose-tracking) to treat it as a known object with known CAD model. But for what you described, it's also feasible. You can still run BundleSDF on different videos. The code I pointed above will compute an oriented bounding box from the shape. For the same cheeze box, the result will be mostly the same eventually among different videos. So their poses should be aligned. I recommend to try it out and viz for you to get an idea. 

2)I'm not sure I understand your question. The ply file isn't really much different from obj file. They can both store the object shape. In our demo, we have showed how you can build the new object's model. If you want to save as ply, it will be simple.

**Comment by ZisongXu** [comment]
Thanks a lot! I will try it!
