### ISSUE TITLE
draw 3D box results as video

### ISSUE THREAD

**Issue by briantian1234** [NVlabs/BundleSDF#91]
Hi Dear Bowen:

Can I ask a question about the coordinate centre of the target object?

I want to show the result as video just as the readme.md show.Could you please tell me how to do that?

Thanks a lot!

Best Regards
Brian

**Comment by wenbowen123** [comment]
I just updated the repo. Please refer to this option
https://github.com/NVlabs/BundleSDF/blob/b06fbd416a234a4ed1280ac4e8e79cf42d7efeaf/run_custom.py#L228

**Comment by briantian1234** [comment]
thank you very much
