### ISSUE TITLE
dockerfile:75

### ISSUE THREAD

**Issue by vegetableschick** [NVlabs/BundleSDF#92]
Hello, I want to use BundleSDF on JETSON AGX ORIN, but the JETSON AGX ORIN processor is ARMv8. I modified dockerfile file line 61 RUN CD / && wget - the -quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh - O x86_64 in /miniconda.sh && \ was changed to aarch64 with the following error:

> [13/18] RUN conda init bash &&    echo "conda activate py38" >> ~/.bashrc &&    conda activate py38 &&    pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 &&    pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" &&    pip install trimesh opencv-python wandb matplotlib imageio tqdm open3d ruamel.yaml sacred kornia pymongo pyrender jupyterlab ninja &&    conda install -y -c anaconda scipy:
0.605 no change     /opt/conda/condabin/conda
0.605 no change     /opt/conda/bin/conda
0.605 no change     /opt/conda/bin/conda-env
0.605 no change     /opt/conda/bin/activate
0.605 no change     /opt/conda/bin/deactivate
0.605 no change     /opt/conda/etc/profile.d/conda.sh
0.605 no change     /opt/conda/etc/fish/conf.d/conda.fish
0.605 no change     /opt/conda/shell/condabin/Conda.psm1
0.605 no change     /opt/conda/shell/condabin/conda-hook.ps1
0.605 no change     /opt/conda/lib/python3.11/site-packages/xontrib/conda.xsh
0.605 no change     /opt/conda/etc/profile.d/conda.csh
0.605 modified      /root/.bashrc
0.605 
0.605 ==> For changes to take effect, close and re-open your current shell. <==
0.605 
1.470 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
3.753 ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
3.753 ERROR: No matching distribution found for torch==1.11.0+cu113
------
dockerfile:75
--------------------
  74 |     
  75 | >>> RUN conda init bash &&\
  76 | >>>     echo "conda activate py38" >> ~/.bashrc &&\
  77 | >>>     conda activate py38 &&\
  78 | >>>     pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 &&\
  79 | >>>     pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" &&\
  80 | >>>     pip install trimesh opencv-python wandb matplotlib imageio tqdm open3d ruamel.yaml sacred kornia pymongo pyrender jupyterlab ninja &&\
  81 | >>>     conda install -y -c anaconda scipy
  82 |     
--------------------
ERROR: failed to solve: process "/bin/bash --login -c conda init bash &&    echo \"conda activate py38\" >> ~/.bashrc &&    conda activate py38 &&    pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113 &&    pip install \"git+https://github.com/facebookresearch/pytorch3d.git@stable\" &&    pip install trimesh opencv-python wandb matplotlib imageio tqdm open3d ruamel.yaml sacred kornia pymongo pyrender jupyterlab ninja &&    conda install -y -c anaconda scipy" did not complete successfully: exit code: 1
The problem is on line 75 RUN conda init bash &&\ :?
How can I fix this?

**Comment by wenbowen123** [comment]
we haven't tested on devices like ORIN. Have you tried on GPUs such as 3090, 2080?

**Comment by vegetableschick** [comment]
> 我们还没有在ORIN等设备上进行测试。您是否尝试过 3090、2080 等 GPU？

Sorry, I have special requirements for the use scenario. I need to install the embedded system on the UAV, and the size specifications of the conventional graphics card are not applicable.Will you provide ORIN terminal in the future？

**Comment by wenbowen123** [comment]
From the log, it looks like torch results the error. Can you try other versions?
`ERROR: Could not find a version that satisfies the requirement torch==1.11.0+cu113 (from versions: 1.8.0, 1.8.1, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
3.753 ERROR: No matching distribution found for torch==1.11.0+cu113`

**Comment by wenbowen123** [comment]
As for now we dont have plan to support ORIN.

**Comment by vegetableschick** [comment]
> As for now we dont have plan to add official support to ORIN.

Thank you. I'll try again
