### ISSUE TITLE
compile error with sm86  

### ISSUE THREAD

**Issue by jawaechan** [NVlabs/BundleSDF#93]
Hi, 
   I am compiling the code via build.sh in 3080 GPU, which is sm86 architecture. But I find the following errors.
   
    error: cannot convert ‘boost::shared_ptr<pcl::PointCloud<pcl::PointNormal> >’ to ‘const PointCloudConstPtr&’ {aka ‘const std::shared_ptr<const pcl::PointCloud<pcl::PointNormal> >&’}
  284 |   vox.setInputCloud(cloud_in);
      |                     ^~~~~~~~
      |                     |
      |                     boost::shared_ptr<pcl::PointCloud<pcl::PointNormal> >

error: ‘pcl::geometry’ has not been declared
 2000 |     float dist = pcl::geometry::distance(ptA, ptB);

error: ‘pcl::geometry’ has not been declared
  744 |       float dist = pcl::geometry::distance(PA_world, PB_world);

error: no matching function for call to ‘downsamplePointCloud(pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr&, pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr&, double)’
 1129 |     Utils::downsamplePointCloud(frame->_cloud, cloud, 0.001);

error: no matching function for call to ‘passFilterPointCloud(pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr&, pcl::PointCloud<pcl::PointXYZRGBNormal>::Ptr&, const char [2], double, float)’
 1102 |     Utils::passFilterPointCloud(cloud_raw_depth,cloud_raw_depth,"z",0.1,(*yml)["depth_processing"]["zfar"].as<float>());

Can you help to fix it?

**Comment by wenbowen123** [comment]
Did you try compiling inside the docker?

**Comment by jawaechan** [comment]
No, I compiled outside the docker. But I have solved this issue. 
Now, I can run your code in a conda environment with realsense camera.

**Comment by wang414** [comment]
Hi, I am facing the same problem. How did you fix this problem? Thank you very much.

**Comment by ZijianWu1121** [comment]
> No, I compiled outside the docker. But I have solved this issue. Now, I can run your code in a conda environment with realsense camera.

Can you share how did you solve this problem?
